{
  "$schema": "node_modules/wrangler/config-schema.json",
  "name": "kunai-repo-manager",
  "compatibility_date": "2025-04-29",
  "compatibility_flags": ["nodejs_compat"],
  "pages_build_output_dir": "./dist",
  "observability": {
    "enabled": true,
  },
}
