// GENERATED by @gel/generate v0.6.3

import type {Executor} from "gel";

export type DeletePackageJsonArgs = {
  readonly "repository_id": number;
};

export type DeletePackageJsonReturns = {
  "deleted_package_json": Array<{
    "id": string;
    "last_updated": Date | null;
    "package_version": string;
    "name": string;
    "repository": {
      "clone_url": string | null;
      "allow_auto_merge": boolean | null;
      "allow_forking": boolean | null;
      "allow_merge_commit": boolean | null;
      "allow_rebase_merge": boolean | null;
      "allow_squash_merge": boolean | null;
      "archived": boolean;
      "archive_url": string | null;
      "contents_url": string;
      "contributors_url": string;
      "created_at": string;
      "default_branch": string;
      "delete_branch_on_merge": boolean | null;
      "deployments_url": string;
      "description": string | null;
      "disabled": boolean;
      "downloads_url": string;
      "events_url": string;
      "fork": boolean;
      "forks": number;
      "forks_count": number;
      "forks_url": string | null;
      "full_name": string;
      "has_discussions": boolean;
      "has_downloads": boolean | null;
      "has_issues": boolean | null;
      "has_pages": boolean;
      "has_projects": boolean | null;
      "has_wiki": boolean | null;
      "homepage": string | null;
      "hooks_url": string;
      "html_url": string;
      "is_template": boolean | null;
      "issue_comment_url": string;
      "issue_events_url": string;
      "issues_url": string;
      "keys_url": string;
      "labels_url": string;
      "language": string;
      "languages_url": string;
      "master_branch": string | null;
      "name": string;
      "node_id": string;
      "notifications_url": string;
      "open_issues": number;
      "open_issues_count": number;
      "private": boolean | null;
      "pushed_at": string;
      "size": number;
      "ssh_url": string;
      "stargazers_count": number;
      "topics": Array<string>;
      "updated_at": string;
      "url": string;
      "visibility": ("public" | "private") | null;
      "watchers_count": number;
      "assignees_url": string | null;
      "blobs_url": string | null;
      "branches_url": string | null;
      "collaborators_url": string | null;
      "comments_url": string | null;
      "commits_url": string | null;
      "compare_url": string | null;
      "git_commits_url": string | null;
      "git_refs_url": string | null;
      "git_tags_url": string | null;
      "git_url": string | null;
      "merges_url": string | null;
      "milestones_url": string | null;
      "mirror_url": string | null;
      "pulls_url": string | null;
      "releases_url": string | null;
      "stargazers_url": string | null;
      "statuses_url": string | null;
      "subscribers_url": string | null;
      "subscription_url": string | null;
      "svn_url": string | null;
      "tags_url": string | null;
      "teams_url": string | null;
      "trees_url": string | null;
      "last_updated": Date | null;
      "id": string;
      "repository_id": number;
      "anonymous_access_enabled": boolean | null;
      "auto_init": boolean | null;
      "custom_properties": unknown | null;
      "merge_commit_message": string | null;
      "merge_commit_title": string | null;
      "network_count": number | null;
      "squash_merge_commit_message": string | null;
      "squash_merge_commit_title": string | null;
      "subscribers_count": number | null;
      "team_id": number | null;
      "temp_clone_token": string | null;
    };
    "dependencies": Array<{
      "dependency_type": ("Dev" | "Prod") | null;
      "last_updated": Date | null;
      "id": string;
      "name": string;
      "dependency_version": string;
    }>;
    "dev_dependencies": Array<{
      "dependency_type": ("Dev" | "Prod") | null;
      "last_updated": Date | null;
      "id": string;
      "name": string;
      "dependency_version": string;
    }>;
  }>;
  "deleted_dependencies": Array<{
    "id": string;
    "last_updated": Date | null;
    "dependency_type": ("Dev" | "Prod") | null;
    "name": string;
    "dependency_version": string;
    "repository": {
      "clone_url": string | null;
      "allow_auto_merge": boolean | null;
      "allow_forking": boolean | null;
      "allow_merge_commit": boolean | null;
      "allow_rebase_merge": boolean | null;
      "allow_squash_merge": boolean | null;
      "archived": boolean;
      "archive_url": string | null;
      "contents_url": string;
      "contributors_url": string;
      "created_at": string;
      "default_branch": string;
      "delete_branch_on_merge": boolean | null;
      "deployments_url": string;
      "description": string | null;
      "disabled": boolean;
      "downloads_url": string;
      "events_url": string;
      "fork": boolean;
      "forks": number;
      "forks_count": number;
      "forks_url": string | null;
      "full_name": string;
      "has_discussions": boolean;
      "has_downloads": boolean | null;
      "has_issues": boolean | null;
      "has_pages": boolean;
      "has_projects": boolean | null;
      "has_wiki": boolean | null;
      "homepage": string | null;
      "hooks_url": string;
      "html_url": string;
      "is_template": boolean | null;
      "issue_comment_url": string;
      "issue_events_url": string;
      "issues_url": string;
      "keys_url": string;
      "labels_url": string;
      "language": string;
      "languages_url": string;
      "master_branch": string | null;
      "name": string;
      "node_id": string;
      "notifications_url": string;
      "open_issues": number;
      "open_issues_count": number;
      "private": boolean | null;
      "pushed_at": string;
      "size": number;
      "ssh_url": string;
      "stargazers_count": number;
      "topics": Array<string>;
      "updated_at": string;
      "url": string;
      "visibility": ("public" | "private") | null;
      "watchers_count": number;
      "assignees_url": string | null;
      "blobs_url": string | null;
      "branches_url": string | null;
      "collaborators_url": string | null;
      "comments_url": string | null;
      "commits_url": string | null;
      "compare_url": string | null;
      "git_commits_url": string | null;
      "git_refs_url": string | null;
      "git_tags_url": string | null;
      "git_url": string | null;
      "merges_url": string | null;
      "milestones_url": string | null;
      "mirror_url": string | null;
      "pulls_url": string | null;
      "releases_url": string | null;
      "stargazers_url": string | null;
      "statuses_url": string | null;
      "subscribers_url": string | null;
      "subscription_url": string | null;
      "svn_url": string | null;
      "tags_url": string | null;
      "teams_url": string | null;
      "trees_url": string | null;
      "last_updated": Date | null;
      "id": string;
      "repository_id": number;
      "anonymous_access_enabled": boolean | null;
      "auto_init": boolean | null;
      "custom_properties": unknown | null;
      "merge_commit_message": string | null;
      "merge_commit_title": string | null;
      "network_count": number | null;
      "squash_merge_commit_message": string | null;
      "squash_merge_commit_title": string | null;
      "subscribers_count": number | null;
      "team_id": number | null;
      "temp_clone_token": string | null;
    };
    "package_json": {
      "name": string;
      "package_version": string;
      "last_updated": Date | null;
      "id": string;
    };
  }>;
};

export function deletePackageJson(client: Executor, args: DeletePackageJsonArgs): Promise<DeletePackageJsonReturns> {
  return client.queryRequiredSingle(`\
with DeletedPackageJson := (
    delete PackageJson 
    filter .repository.repository_id = <int64>$repository_id
),
DeletedDependencies := (
    delete Dependency 
    filter .package_json.repository.repository_id = <int64>$repository_id
)
select {
    deleted_package_json := DeletedPackageJson {**},
    deleted_dependencies := DeletedDependencies {**}
};`, args);

}
