// GENERATED by @gel/generate v0.6.3

import type {Executor} from "gel";


export type GetAllPackageJsonsReturns = Array<{
  "repository_id": number;
  "name": string;
  "package_version": string;
  "id": string;
  "last_updated": Date | null;
  "dependencies": Array<{
    "dependency_type": ("Dev" | "Prod");
    "dependency_version": string;
    "id": string;
    "last_updated": Date | null;
    "name": string;
    "repository_id": number;
  }>;
  "dev_dependencies": Array<{
    "dependency_type": ("Dev" | "Prod");
    "dependency_version": string;
    "id": string;
    "last_updated": Date | null;
    "name": string;
    "repository_id": number;
  }>;
}>;

export function getAllPackageJsons(client: Executor): Promise<GetAllPackageJsonsReturns> {
  return client.query(`\
# return all packageJsons
select PackageJson { ** };`);

}
