// GENERATED by @gel/generate v0.6.3

import type {Executor} from "gel";

export type GetDependenciesForRepoArgs = {
  readonly "repository_id": number;
};

export type GetDependenciesForRepoReturns = Array<{
  "dependency_version": string;
  "id": string;
  "name": string;
  "dependency_type": ("Dev" | "Prod") | null;
  "last_updated": Date | null;
  "package_json": {
    "id": string;
    "name": string;
    "package_version": string;
    "last_updated": Date | null;
  };
  "repository": {
    "archived": boolean;
    "contents_url": string;
    "contributors_url": string;
    "created_at": string;
    "default_branch": string;
    "deployments_url": string;
    "disabled": boolean;
    "downloads_url": string;
    "events_url": string;
    "fork": boolean;
    "forks": number;
    "forks_count": number;
    "full_name": string;
    "has_discussions": boolean;
    "has_pages": boolean;
    "hooks_url": string;
    "html_url": string;
    "id": string;
    "issue_comment_url": string;
    "issue_events_url": string;
    "issues_url": string;
    "keys_url": string;
    "labels_url": string;
    "language": string;
    "languages_url": string;
    "name": string;
    "node_id": string;
    "notifications_url": string;
    "open_issues": number;
    "open_issues_count": number;
    "pushed_at": string;
    "repository_id": number;
    "size": number;
    "ssh_url": string;
    "stargazers_count": number;
    "updated_at": string;
    "url": string;
    "watchers_count": number;
    "allow_auto_merge": boolean | null;
    "allow_forking": boolean | null;
    "allow_merge_commit": boolean | null;
    "allow_rebase_merge": boolean | null;
    "allow_squash_merge": boolean | null;
    "anonymous_access_enabled": boolean | null;
    "archive_url": string | null;
    "assignees_url": string | null;
    "auto_init": boolean | null;
    "blobs_url": string | null;
    "branches_url": string | null;
    "clone_url": string | null;
    "collaborators_url": string | null;
    "comments_url": string | null;
    "commits_url": string | null;
    "compare_url": string | null;
    "delete_branch_on_merge": boolean | null;
    "description": string | null;
    "forks_url": string | null;
    "git_commits_url": string | null;
    "git_refs_url": string | null;
    "git_tags_url": string | null;
    "git_url": string | null;
    "has_downloads": boolean | null;
    "has_issues": boolean | null;
    "has_projects": boolean | null;
    "has_wiki": boolean | null;
    "homepage": string | null;
    "is_template": boolean | null;
    "last_updated": Date | null;
    "master_branch": string | null;
    "merge_commit_message": string | null;
    "merge_commit_title": string | null;
    "merges_url": string | null;
    "milestones_url": string | null;
    "mirror_url": string | null;
    "network_count": number | null;
    "private": boolean | null;
    "pulls_url": string | null;
    "releases_url": string | null;
    "squash_merge_commit_message": string | null;
    "squash_merge_commit_title": string | null;
    "stargazers_url": string | null;
    "statuses_url": string | null;
    "subscribers_count": number | null;
    "subscribers_url": string | null;
    "subscription_url": string | null;
    "svn_url": string | null;
    "tags_url": string | null;
    "team_id": number | null;
    "teams_url": string | null;
    "temp_clone_token": string | null;
    "trees_url": string | null;
    "visibility": ("public" | "private") | null;
    "topics": Array<string>;
  };
}>;

export function getDependenciesForRepo(client: Executor, args: GetDependenciesForRepoArgs): Promise<GetDependenciesForRepoReturns> {
  return client.query(`\
# Get all dependencies for a single repository by repository_id
select Dependency {
  **
} filter .repository.repository_id = <int64>$repository_id;`, args);

}
