// GENERATED by @gel/generate v0.6.3

import type {Executor} from "gel";

export type GetDependencyArgs = {
  readonly "dependency_type"?: ("Dev" | "Prod") | null;
  readonly "name"?: string | null;
  readonly "dependency_version"?: string | null;
};

export type GetDependencyReturns = Array<{
  "dependency_version": string;
  "name": string;
  "repository_id": number;
  "id": string;
  "dependency_type": ("Dev" | "Prod");
  "last_updated": Date | null;
  "package_json": {
    "repository_id": number;
    "name": string;
    "package_version": string;
    "id": string;
    "last_updated": Date | null;
  } | null;
}>;

export function getDependency(client: Executor, args: GetDependencyArgs): Promise<GetDependencyReturns> {
  return client.query(`\
# get Dependency by dependency type
select Dependency { **
} filter assert_exists(Dependency.dependency_type) ?= <optional DependencyType>$dependency_type;

# get packageJson by dependency name
select Dependency { **
} filter assert_exists(Dependency.name) ?= <optional str>$name;

# get packageJson by dependency version
select Dependency { **
} filter assert_exists(Dependency.dependency_version) ?= <optional str>$dependency_version;

select Dependency { ** };

# This is all one query, but it's split up for readability. All filters are optional. 
# If no filters are provided, all Dependencies will be returned.`, args);

}
