// GENERATED by @gel/generate v0.6.3

import type {Executor} from "gel";

export type GetFilePathArgs = {
  readonly "repository_id"?: number | null;
};

export type GetFilePathReturns = {
  "last_updated": Date | null;
  "id": string;
  "file_name": string;
  "file_type": ("PNG" | "JPG" | "JPEG" | "GIF" | "SVG" | "PSD" | "JSON" | "MD" | "TXT" | "LOG" | "ZIP" | "GEL" | "TOML" | "YML" | "YAML" | "JSONC" | "WOFF2" | "CSS" | "TS" | "TSX" | "JS" | "EDGEQL" | "XML" | "PDF" | "CSV" | "SQL" | "HTML");
  "path": string;
  "repository": {
    "id": string;
    "repository_id": number;
    "allow_auto_merge": boolean | null;
    "allow_forking": boolean | null;
    "allow_merge_commit": boolean | null;
    "allow_rebase_merge": boolean | null;
    "allow_squash_merge": boolean | null;
    "archive_url": string | null;
    "archived": boolean;
    "assignees_url": string | null;
    "blobs_url": string | null;
    "branches_url": string | null;
    "clone_url": string | null;
    "collaborators_url": string | null;
    "comments_url": string | null;
    "commits_url": string | null;
    "compare_url": string | null;
    "contents_url": string;
    "contributors_url": string;
    "created_at": string;
    "default_branch": string;
    "delete_branch_on_merge": boolean | null;
    "deployments_url": string;
    "description": string | null;
    "disabled": boolean;
    "downloads_url": string;
    "events_url": string;
    "fork": boolean;
    "forks": number;
    "forks_count": number;
    "forks_url": string | null;
    "full_name": string;
    "git_commits_url": string | null;
    "git_refs_url": string | null;
    "git_tags_url": string | null;
    "git_url": string | null;
    "has_discussions": boolean;
    "has_downloads": boolean | null;
    "has_issues": boolean | null;
    "has_pages": boolean;
    "has_projects": boolean | null;
    "has_wiki": boolean | null;
    "homepage": string | null;
    "hooks_url": string;
    "html_url": string;
    "is_template": boolean | null;
    "issue_comment_url": string;
    "issue_events_url": string;
    "issues_url": string;
    "keys_url": string;
    "labels_url": string;
    "language": string;
    "languages_url": string;
    "master_branch": string | null;
    "merges_url": string | null;
    "milestones_url": string | null;
    "mirror_url": string | null;
    "name": string;
    "node_id": string;
    "notifications_url": string;
    "open_issues": number;
    "open_issues_count": number;
    "private": boolean | null;
    "pulls_url": string | null;
    "pushed_at": string;
    "releases_url": string | null;
    "size": number;
    "ssh_url": string;
    "stargazers_count": number;
    "stargazers_url": string | null;
    "statuses_url": string | null;
    "subscribers_url": string | null;
    "subscription_url": string | null;
    "svn_url": string | null;
    "tags_url": string | null;
    "teams_url": string | null;
    "topics": Array<string>;
    "trees_url": string | null;
    "updated_at": string;
    "url": string;
    "visibility": ("public" | "private") | null;
    "watchers_count": number;
    "last_updated": Date | null;
    "anonymous_access_enabled": boolean | null;
    "auto_init": boolean | null;
    "merge_commit_message": string | null;
    "merge_commit_title": string | null;
    "network_count": number | null;
    "squash_merge_commit_message": string | null;
    "squash_merge_commit_title": string | null;
    "subscribers_count": number | null;
    "team_id": number | null;
    "temp_clone_token": string | null;
  };
} | null;

export function getFilePath(client: Executor, args: GetFilePathArgs): Promise<GetFilePathReturns> {
  return client.querySingle(`\
# get FilePath by repoID
select assert_single(
  FilePath { ** }
  filter assert_exists(Repository.repository_id) ?= <optional int64>$repository_id
  and FilePath.file_type = FileType.JSON
) limit 1;`, args);

}
