with NewOrganization := (insert Organization {
     organization_id:= <int64>$organization_id,
     login:= <str>$login,
     avatar_url:= <str>$avatar_url,
     name:= <optional str>$name,
     email:= <optional str>$email,
     node_id:= <str>$node_id,
     gravatar_id:= <str>$gravatar_id,
     url:= <str>$url,
     html_url:= <str>$html_url,
     followers_url:= <str>$followers_url,
     following_url:= <str>$following_url,
     gists_url:= <str>$gists_url,
     starred_url:= <str>$starred_url,
     subscriptions_url:= <str>$subscriptions_url,
     organizations_url:= <str>$organizations_url,
     repos_url:= <str>$repos_url,
     events_url:= <str>$events_url,
     received_events_url:= <str>$received_events_url,
     role_type:= <str>$role_type,
     site_admin:= <bool>$site_admin,
     starred_at:= <optional str>$starred_at,
     user_view_type:= <optional str>$user_view_type,
     webhook_id:= <optional int64>$webhook_id,
     webhook_url:= <optional str>$webhook_url,
    }
  unless conflict on .login
  else (
    update Organization 
    filter .login = <str>$login
    set {
     organization_id:= <int64>$organization_id,
     login:= <str>$login,
     avatar_url:= <str>$avatar_url,
     name:= <optional str>$name,
     email:= <optional str>$email,
     node_id:= <str>$node_id,
     gravatar_id:= <str>$gravatar_id,
     url:= <str>$url,
     html_url:= <str>$html_url,
     followers_url:= <str>$followers_url,
     following_url:= <str>$following_url,
     gists_url:= <str>$gists_url,
     starred_url:= <str>$starred_url,
     subscriptions_url:= <str>$subscriptions_url,
     organizations_url:= <str>$organizations_url,
     repos_url:= <str>$repos_url,
     events_url:= <str>$events_url,
     received_events_url:= <str>$received_events_url,
     role_type:= <str>$role_type,
     site_admin:= <bool>$site_admin,
     starred_at:= <optional str>$starred_at,
     user_view_type:= <optional str>$user_view_type,
     webhook_id:= <optional int64>$webhook_id,
     webhook_url:= <optional str>$webhook_url,
    }
  )
)
select NewOrganization {
    id,
    organization_id,
    login,
    avatar_url,
    name,
    email,
    node_id,
    gravatar_id,
    url,
    html_url,
    followers_url,
    following_url,
    gists_url,
    starred_url,
    subscriptions_url,
    organizations_url,
    repos_url,
    events_url,
    received_events_url,
    role_type,
    site_admin,
    starred_at,
    user_view_type,
    webhook_id,
    webhook_url,
    last_updated
};
