// GENERATED by @gel/generate v0.6.3

import type {Executor} from "gel";

export type InsertOrUpdatePackageJsonArgs = {
  readonly "name": string;
  readonly "package_version": string;
  readonly "repository": string;
  readonly "dependencies": ReadonlyArray<{
  readonly "name": string;
  readonly "dependency_version": string;
}>;
  readonly "dev_dependencies": ReadonlyArray<{
  readonly "name": string;
  readonly "dependency_version": string;
}>;
};

export type InsertOrUpdatePackageJsonReturns = {
  "last_updated": Date | null;
  "package_version": string;
  "name": string;
  "id": string;
  "repository": {
    "id": string;
    "allow_auto_merge": boolean | null;
    "allow_forking": boolean | null;
    "allow_merge_commit": boolean | null;
    "allow_rebase_merge": boolean | null;
    "allow_squash_merge": boolean | null;
    "archived": boolean;
    "contents_url": string;
    "contributors_url": string;
    "created_at": string;
    "default_branch": string;
    "delete_branch_on_merge": boolean | null;
    "deployments_url": string;
    "disabled": boolean;
    "downloads_url": string;
    "events_url": string;
    "fork": boolean;
    "forks": number;
    "forks_count": number;
    "forks_url": string | null;
    "full_name": string;
    "has_discussions": boolean;
    "has_pages": boolean;
    "hooks_url": string;
    "html_url": string;
    "issue_comment_url": string;
    "issue_events_url": string;
    "issues_url": string;
    "keys_url": string;
    "labels_url": string;
    "language": string;
    "languages_url": string;
    "master_branch": string | null;
    "name": string;
    "node_id": string;
    "notifications_url": string;
    "open_issues": number;
    "open_issues_count": number;
    "pushed_at": string;
    "size": number;
    "ssh_url": string;
    "stargazers_count": number;
    "topics": Array<string>;
    "updated_at": string;
    "url": string;
    "watchers_count": number;
    "last_updated": Date | null;
    "archive_url": string | null;
    "assignees_url": string | null;
    "blobs_url": string | null;
    "branches_url": string | null;
    "clone_url": string | null;
    "collaborators_url": string | null;
    "comments_url": string | null;
    "commits_url": string | null;
    "compare_url": string | null;
    "git_commits_url": string | null;
    "git_refs_url": string | null;
    "git_tags_url": string | null;
    "git_url": string | null;
    "merges_url": string | null;
    "milestones_url": string | null;
    "mirror_url": string | null;
    "pulls_url": string | null;
    "releases_url": string | null;
    "stargazers_url": string | null;
    "statuses_url": string | null;
    "subscribers_url": string | null;
    "subscription_url": string | null;
    "svn_url": string | null;
    "tags_url": string | null;
    "teams_url": string | null;
    "trees_url": string | null;
    "repository_id": number;
    "anonymous_access_enabled": boolean | null;
    "auto_init": boolean | null;
    "description": string | null;
    "has_downloads": boolean | null;
    "has_issues": boolean | null;
    "has_projects": boolean | null;
    "has_wiki": boolean | null;
    "homepage": string | null;
    "is_template": boolean | null;
    "merge_commit_message": string | null;
    "merge_commit_title": string | null;
    "network_count": number | null;
    "private": boolean | null;
    "squash_merge_commit_message": string | null;
    "squash_merge_commit_title": string | null;
    "subscribers_count": number | null;
    "team_id": number | null;
    "temp_clone_token": string | null;
    "visibility": ("public" | "private") | null;
  };
  "dependencies": Array<{
    "last_updated": Date | null;
    "name": string;
    "dependency_version": string;
    "id": string;
    "dependency_type": ("Dev" | "Prod") | null;
  }>;
  "dev_dependencies": Array<{
    "last_updated": Date | null;
    "name": string;
    "dependency_version": string;
    "id": string;
    "dependency_type": ("Dev" | "Prod") | null;
  }>;
} | null;

export function insertOrUpdatePackageJson(client: Executor, args: InsertOrUpdatePackageJsonArgs): Promise<InsertOrUpdatePackageJsonReturns> {
  return client.querySingle(`\
with 
  NewPackageJson := (
    insert PackageJson {
      name := <str>$name,
      package_version := <str>$package_version,
      repository := (
        select Repository
        filter .name = <str>$repository
        limit 1
      )
    }
    unless conflict on .repository 
    else (
      update PackageJson
      filter .repository.name = <str>$repository
      set {
        name := <str>$name,
        package_version := <str>$package_version,
        repository := (
          select Repository
          filter .name = <str>$repository
          limit 1
        ),
      }
    )
  ),

  InsertProdDependencies := (
    for dependency in array_unpack(<array<tuple<name: str, dependency_version: str>>>$dependencies)
    union (
      insert ProdDependency {
        name := <str>dependency.name,
        dependency_version := <str>dependency.dependency_version,
        package_json := NewPackageJson,
        repository := NewPackageJson.repository,
      }
      unless conflict on (.dependency_type, .name, .repository)
      else (
        update ProdDependency
        filter .name = <str>dependency.name
          and .repository = NewPackageJson.repository
        set {
          dependency_version := <str>dependency.dependency_version,
        }
      )
    )
  ),

  InsertDevDependencies := (
    for dev_dependency in array_unpack(<array<tuple<name: str, dependency_version: str>>>$dev_dependencies)
    union (
      insert DevDependency {
        name := <str>dev_dependency.name,
        dependency_version := <str>dev_dependency.dependency_version,
        package_json := NewPackageJson,
        repository := NewPackageJson.repository,
      }
      unless conflict on (.dependency_type, .name, .repository)
      else (
        update DevDependency
        filter .name = <str>dev_dependency.name
          and .repository = NewPackageJson.repository
        set {
          dependency_version := <str>dev_dependency.dependency_version,
        }
      )
    )
  )

select NewPackageJson { ** };`, args);

}
