// GENERATED by @gel/generate v0.6.3

import type {Executor} from "gel";

export type DeletePackageJsonArgs = {
  readonly "repository_id": number;
};

export type DeletePackageJsonReturns = {
  "deleted_package_json": {
    "id": string;
    "name": string;
    "package_version": string;
    "last_updated": Date | null;
    "dependencies": Array<{
      "dependency_version": string;
      "id": string;
      "name": string;
      "dependency_type": ("Dev" | "Prod") | null;
      "last_updated": Date | null;
    }>;
    "dev_dependencies": Array<{
      "dependency_version": string;
      "id": string;
      "name": string;
      "dependency_type": ("Dev" | "Prod") | null;
      "last_updated": Date | null;
    }>;
    "repository": {
      "archived": boolean;
      "contents_url": string;
      "contributors_url": string;
      "created_at": string;
      "default_branch": string;
      "deployments_url": string;
      "disabled": boolean;
      "downloads_url": string;
      "events_url": string;
      "fork": boolean;
      "forks": number;
      "forks_count": number;
      "full_name": string;
      "has_discussions": boolean;
      "has_pages": boolean;
      "hooks_url": string;
      "html_url": string;
      "id": string;
      "issue_comment_url": string;
      "issue_events_url": string;
      "issues_url": string;
      "keys_url": string;
      "labels_url": string;
      "language": string;
      "languages_url": string;
      "name": string;
      "node_id": string;
      "notifications_url": string;
      "open_issues": number;
      "open_issues_count": number;
      "pushed_at": string;
      "repository_id": number;
      "size": number;
      "ssh_url": string;
      "stargazers_count": number;
      "updated_at": string;
      "url": string;
      "watchers_count": number;
      "allow_auto_merge": boolean | null;
      "allow_forking": boolean | null;
      "allow_merge_commit": boolean | null;
      "allow_rebase_merge": boolean | null;
      "allow_squash_merge": boolean | null;
      "anonymous_access_enabled": boolean | null;
      "archive_url": string | null;
      "assignees_url": string | null;
      "auto_init": boolean | null;
      "blobs_url": string | null;
      "branches_url": string | null;
      "clone_url": string | null;
      "collaborators_url": string | null;
      "comments_url": string | null;
      "commits_url": string | null;
      "compare_url": string | null;
      "delete_branch_on_merge": boolean | null;
      "description": string | null;
      "forks_url": string | null;
      "git_commits_url": string | null;
      "git_refs_url": string | null;
      "git_tags_url": string | null;
      "git_url": string | null;
      "has_downloads": boolean | null;
      "has_issues": boolean | null;
      "has_projects": boolean | null;
      "has_wiki": boolean | null;
      "homepage": string | null;
      "is_template": boolean | null;
      "last_updated": Date | null;
      "master_branch": string | null;
      "merge_commit_message": string | null;
      "merge_commit_title": string | null;
      "merges_url": string | null;
      "milestones_url": string | null;
      "mirror_url": string | null;
      "network_count": number | null;
      "private": boolean | null;
      "pulls_url": string | null;
      "releases_url": string | null;
      "squash_merge_commit_message": string | null;
      "squash_merge_commit_title": string | null;
      "stargazers_url": string | null;
      "statuses_url": string | null;
      "subscribers_count": number | null;
      "subscribers_url": string | null;
      "subscription_url": string | null;
      "svn_url": string | null;
      "tags_url": string | null;
      "team_id": number | null;
      "teams_url": string | null;
      "temp_clone_token": string | null;
      "trees_url": string | null;
      "visibility": ("public" | "private") | null;
      "topics": Array<string>;
    };
  } | null;
};

export function deletePackageJson(client: Executor, args: DeletePackageJsonArgs): Promise<DeletePackageJsonReturns> {
  return client.queryRequiredSingle(`\
with DeletedPackageJson := (
    delete PackageJson 
    filter .repository.repository_id = <int64>$repository_id
)
select {
    deleted_package_json := DeletedPackageJson {**},
};`, args);

}



export type GetRepositoriesReturns = Array<{
  "archived": boolean;
  "contents_url": string;
  "contributors_url": string;
  "created_at": string;
  "default_branch": string;
  "deployments_url": string;
  "disabled": boolean;
  "downloads_url": string;
  "events_url": string;
  "fork": boolean;
  "forks": number;
  "forks_count": number;
  "full_name": string;
  "has_discussions": boolean;
  "has_pages": boolean;
  "hooks_url": string;
  "html_url": string;
  "id": string;
  "issue_comment_url": string;
  "issue_events_url": string;
  "issues_url": string;
  "keys_url": string;
  "labels_url": string;
  "language": string;
  "languages_url": string;
  "name": string;
  "node_id": string;
  "notifications_url": string;
  "open_issues": number;
  "open_issues_count": number;
  "pushed_at": string;
  "repository_id": number;
  "size": number;
  "ssh_url": string;
  "stargazers_count": number;
  "updated_at": string;
  "url": string;
  "watchers_count": number;
  "allow_auto_merge": boolean | null;
  "allow_forking": boolean | null;
  "allow_merge_commit": boolean | null;
  "allow_rebase_merge": boolean | null;
  "allow_squash_merge": boolean | null;
  "anonymous_access_enabled": boolean | null;
  "archive_url": string | null;
  "assignees_url": string | null;
  "auto_init": boolean | null;
  "blobs_url": string | null;
  "branches_url": string | null;
  "clone_url": string | null;
  "collaborators_url": string | null;
  "comments_url": string | null;
  "commits_url": string | null;
  "compare_url": string | null;
  "delete_branch_on_merge": boolean | null;
  "description": string | null;
  "forks_url": string | null;
  "git_commits_url": string | null;
  "git_refs_url": string | null;
  "git_tags_url": string | null;
  "git_url": string | null;
  "has_downloads": boolean | null;
  "has_issues": boolean | null;
  "has_projects": boolean | null;
  "has_wiki": boolean | null;
  "homepage": string | null;
  "is_template": boolean | null;
  "last_updated": Date | null;
  "master_branch": string | null;
  "merge_commit_message": string | null;
  "merge_commit_title": string | null;
  "merges_url": string | null;
  "milestones_url": string | null;
  "mirror_url": string | null;
  "network_count": number | null;
  "private": boolean | null;
  "pulls_url": string | null;
  "releases_url": string | null;
  "squash_merge_commit_message": string | null;
  "squash_merge_commit_title": string | null;
  "stargazers_url": string | null;
  "statuses_url": string | null;
  "subscribers_count": number | null;
  "subscribers_url": string | null;
  "subscription_url": string | null;
  "svn_url": string | null;
  "tags_url": string | null;
  "team_id": number | null;
  "teams_url": string | null;
  "temp_clone_token": string | null;
  "trees_url": string | null;
  "visibility": ("public" | "private") | null;
  "all_dependencies": Array<{
    "dependency_version": string;
    "id": string;
    "name": string;
    "dependency_type": ("Dev" | "Prod") | null;
    "last_updated": Date | null;
  }>;
  "all_file_paths": Array<{
    "file_name": string;
    "file_type": ("PNG" | "JPG" | "JPEG" | "GIF" | "SVG" | "PSD" | "JSON" | "MD" | "TXT" | "LOG" | "ZIP" | "GEL" | "TOML" | "YML" | "YAML" | "JSONC" | "WOFF2" | "CSS" | "TS" | "TSX" | "JS" | "EDGEQL" | "XML" | "PDF" | "CSV" | "SQL" | "HTML");
    "id": string;
    "path": string;
    "last_updated": Date | null;
  }>;
  "package_json": Array<{
    "id": string;
    "name": string;
    "package_version": string;
    "last_updated": Date | null;
  }>;
  "topics": Array<string>;
  "owner": {
    "avatar_url": string;
    "email": string;
    "id": string;
    "login": string;
    "name": string;
    "role_type": string;
    "site_admin": boolean;
    "user_id": number;
    "events_url": string | null;
    "followers_url": string | null;
    "following_url": string | null;
    "gists_url": string | null;
    "gravatar_id": string | null;
    "html_url": string | null;
    "last_updated": Date | null;
    "node_id": string | null;
    "organizations_url": string | null;
    "received_events_url": string | null;
    "repos_url": string | null;
    "starred_at": string | null;
    "starred_url": string | null;
    "subscriptions_url": string | null;
    "url": string | null;
    "user_view_type": string | null;
  };
  "code_of_conduct": {
    "id": string;
    "key": string | null;
    "last_updated": Date | null;
    "name": string | null;
    "node_id": string | null;
    "spdx_id": string | null;
    "url": string | null;
  } | null;
  "license": {
    "id": string;
    "key": string;
    "name": string;
    "node_id": string;
    "html_url": string | null;
    "last_updated": Date | null;
    "spdx_id": string | null;
    "url": string | null;
  } | null;
  "organization": {
    "avatar_url": string;
    "events_url": string;
    "followers_url": string;
    "following_url": string;
    "gists_url": string;
    "gravatar_id": string;
    "html_url": string;
    "id": string;
    "login": string;
    "node_id": string;
    "organizations_url": string;
    "received_events_url": string;
    "repos_url": string;
    "role_type": string;
    "site_admin": boolean;
    "starred_url": string;
    "subscriptions_url": string;
    "url": string;
    "email": string | null;
    "last_updated": Date | null;
    "name": string | null;
    "organization_id": number | null;
    "starred_at": string | null;
    "user_view_type": string | null;
  } | null;
  "security_and_analysis": {
    "id": string;
    "advanced_security_status": string | null;
    "code_security_status": string | null;
    "dependabot_security_updates_status": string | null;
    "last_updated": Date | null;
    "secret_scanning_ai_detection_status": string | null;
    "secret_scanning_non_provider_patterns_status": string | null;
    "secret_scanning_push_protection_status": string | null;
    "secret_scanning_status": string | null;
  } | null;
  "template_repository": {
    "archived": boolean;
    "contents_url": string;
    "contributors_url": string;
    "created_at": string;
    "default_branch": string;
    "deployments_url": string;
    "disabled": boolean;
    "downloads_url": string;
    "events_url": string;
    "fork": boolean;
    "forks": number;
    "forks_count": number;
    "full_name": string;
    "has_discussions": boolean;
    "has_pages": boolean;
    "hooks_url": string;
    "html_url": string;
    "id": string;
    "issue_comment_url": string;
    "issue_events_url": string;
    "issues_url": string;
    "keys_url": string;
    "labels_url": string;
    "language": string;
    "languages_url": string;
    "name": string;
    "node_id": string;
    "notifications_url": string;
    "open_issues": number;
    "open_issues_count": number;
    "pushed_at": string;
    "repository_id": number;
    "size": number;
    "ssh_url": string;
    "stargazers_count": number;
    "updated_at": string;
    "url": string;
    "watchers_count": number;
    "allow_auto_merge": boolean | null;
    "allow_forking": boolean | null;
    "allow_merge_commit": boolean | null;
    "allow_rebase_merge": boolean | null;
    "allow_squash_merge": boolean | null;
    "anonymous_access_enabled": boolean | null;
    "archive_url": string | null;
    "assignees_url": string | null;
    "auto_init": boolean | null;
    "blobs_url": string | null;
    "branches_url": string | null;
    "clone_url": string | null;
    "collaborators_url": string | null;
    "comments_url": string | null;
    "commits_url": string | null;
    "compare_url": string | null;
    "delete_branch_on_merge": boolean | null;
    "description": string | null;
    "forks_url": string | null;
    "git_commits_url": string | null;
    "git_refs_url": string | null;
    "git_tags_url": string | null;
    "git_url": string | null;
    "has_downloads": boolean | null;
    "has_issues": boolean | null;
    "has_projects": boolean | null;
    "has_wiki": boolean | null;
    "homepage": string | null;
    "is_template": boolean | null;
    "last_updated": Date | null;
    "master_branch": string | null;
    "merge_commit_message": string | null;
    "merge_commit_title": string | null;
    "merges_url": string | null;
    "milestones_url": string | null;
    "mirror_url": string | null;
    "network_count": number | null;
    "private": boolean | null;
    "pulls_url": string | null;
    "releases_url": string | null;
    "squash_merge_commit_message": string | null;
    "squash_merge_commit_title": string | null;
    "stargazers_url": string | null;
    "statuses_url": string | null;
    "subscribers_count": number | null;
    "subscribers_url": string | null;
    "subscription_url": string | null;
    "svn_url": string | null;
    "tags_url": string | null;
    "team_id": number | null;
    "teams_url": string | null;
    "temp_clone_token": string | null;
    "trees_url": string | null;
    "visibility": ("public" | "private") | null;
    "topics": Array<string>;
  } | null;
  "user": {
    "avatar_url": string;
    "email": string;
    "id": string;
    "login": string;
    "name": string;
    "role_type": string;
    "site_admin": boolean;
    "user_id": number;
    "events_url": string | null;
    "followers_url": string | null;
    "following_url": string | null;
    "gists_url": string | null;
    "gravatar_id": string | null;
    "html_url": string | null;
    "last_updated": Date | null;
    "node_id": string | null;
    "organizations_url": string | null;
    "received_events_url": string | null;
    "repos_url": string | null;
    "starred_at": string | null;
    "starred_url": string | null;
    "subscriptions_url": string | null;
    "url": string | null;
    "user_view_type": string | null;
  } | null;
}>;

export function getRepositories(client: Executor): Promise<GetRepositoriesReturns> {
  return client.query(`\
select Repository { **
};

# This is all one query, but it's split up for readability. All filters are optional. 
# If no filters are provided, all Repositories will be returned.`);

}


export type GetPackageJsonArgs = {
  readonly "name"?: string | null;
  readonly "repository_id"?: number | null;
};

export type GetPackageJsonReturns = {
  "id": string;
  "name": string;
  "package_version": string;
  "last_updated": Date | null;
  "dependencies": Array<{
    "dependency_version": string;
    "id": string;
    "name": string;
    "dependency_type": ("Dev" | "Prod") | null;
    "last_updated": Date | null;
  }>;
  "dev_dependencies": Array<{
    "dependency_version": string;
    "id": string;
    "name": string;
    "dependency_type": ("Dev" | "Prod") | null;
    "last_updated": Date | null;
  }>;
  "repository": {
    "archived": boolean;
    "contents_url": string;
    "contributors_url": string;
    "created_at": string;
    "default_branch": string;
    "deployments_url": string;
    "disabled": boolean;
    "downloads_url": string;
    "events_url": string;
    "fork": boolean;
    "forks": number;
    "forks_count": number;
    "full_name": string;
    "has_discussions": boolean;
    "has_pages": boolean;
    "hooks_url": string;
    "html_url": string;
    "id": string;
    "issue_comment_url": string;
    "issue_events_url": string;
    "issues_url": string;
    "keys_url": string;
    "labels_url": string;
    "language": string;
    "languages_url": string;
    "name": string;
    "node_id": string;
    "notifications_url": string;
    "open_issues": number;
    "open_issues_count": number;
    "pushed_at": string;
    "repository_id": number;
    "size": number;
    "ssh_url": string;
    "stargazers_count": number;
    "updated_at": string;
    "url": string;
    "watchers_count": number;
    "allow_auto_merge": boolean | null;
    "allow_forking": boolean | null;
    "allow_merge_commit": boolean | null;
    "allow_rebase_merge": boolean | null;
    "allow_squash_merge": boolean | null;
    "anonymous_access_enabled": boolean | null;
    "archive_url": string | null;
    "assignees_url": string | null;
    "auto_init": boolean | null;
    "blobs_url": string | null;
    "branches_url": string | null;
    "clone_url": string | null;
    "collaborators_url": string | null;
    "comments_url": string | null;
    "commits_url": string | null;
    "compare_url": string | null;
    "delete_branch_on_merge": boolean | null;
    "description": string | null;
    "forks_url": string | null;
    "git_commits_url": string | null;
    "git_refs_url": string | null;
    "git_tags_url": string | null;
    "git_url": string | null;
    "has_downloads": boolean | null;
    "has_issues": boolean | null;
    "has_projects": boolean | null;
    "has_wiki": boolean | null;
    "homepage": string | null;
    "is_template": boolean | null;
    "last_updated": Date | null;
    "master_branch": string | null;
    "merge_commit_message": string | null;
    "merge_commit_title": string | null;
    "merges_url": string | null;
    "milestones_url": string | null;
    "mirror_url": string | null;
    "network_count": number | null;
    "private": boolean | null;
    "pulls_url": string | null;
    "releases_url": string | null;
    "squash_merge_commit_message": string | null;
    "squash_merge_commit_title": string | null;
    "stargazers_url": string | null;
    "statuses_url": string | null;
    "subscribers_count": number | null;
    "subscribers_url": string | null;
    "subscription_url": string | null;
    "svn_url": string | null;
    "tags_url": string | null;
    "team_id": number | null;
    "teams_url": string | null;
    "temp_clone_token": string | null;
    "trees_url": string | null;
    "visibility": ("public" | "private") | null;
    "topics": Array<string>;
  };
} | null;

export function getPackageJson(client: Executor, args: GetPackageJsonArgs): Promise<GetPackageJsonReturns> {
  return client.querySingle(`\
# get packageJson by repoID
select assert_single(
  PackageJson { ** }
  filter assert_exists(Repository.repository_id) ?= <optional int64>$repository_id
);

# get packageJson by repo name
select assert_single(
  PackageJson { ** }
  filter assert_exists(Repository.full_name) ?= <optional str>$name
);

# This is all one query, but it's split up for readability. All filters are optional.`, args);

}


export type InsertOrUpdatePackageJsonArgs = {
  readonly "dependencies": ReadonlyArray<{
  readonly "name": string;
  readonly "dependency_version": string;
}>;
  readonly "dev_dependencies": ReadonlyArray<{
  readonly "name": string;
  readonly "dependency_version": string;
}>;
  readonly "name": string;
  readonly "package_version": string;
  readonly "repository": string;
};

export type InsertOrUpdatePackageJsonReturns = {
  "id": string;
  "name": string;
  "package_version": string;
  "last_updated": Date | null;
  "dependencies": Array<{
    "dependency_version": string;
    "id": string;
    "name": string;
    "dependency_type": ("Dev" | "Prod") | null;
    "last_updated": Date | null;
  }>;
  "dev_dependencies": Array<{
    "dependency_version": string;
    "id": string;
    "name": string;
    "dependency_type": ("Dev" | "Prod") | null;
    "last_updated": Date | null;
  }>;
  "repository": {
    "archived": boolean;
    "contents_url": string;
    "contributors_url": string;
    "created_at": string;
    "default_branch": string;
    "deployments_url": string;
    "disabled": boolean;
    "downloads_url": string;
    "events_url": string;
    "fork": boolean;
    "forks": number;
    "forks_count": number;
    "full_name": string;
    "has_discussions": boolean;
    "has_pages": boolean;
    "hooks_url": string;
    "html_url": string;
    "id": string;
    "issue_comment_url": string;
    "issue_events_url": string;
    "issues_url": string;
    "keys_url": string;
    "labels_url": string;
    "language": string;
    "languages_url": string;
    "name": string;
    "node_id": string;
    "notifications_url": string;
    "open_issues": number;
    "open_issues_count": number;
    "pushed_at": string;
    "repository_id": number;
    "size": number;
    "ssh_url": string;
    "stargazers_count": number;
    "updated_at": string;
    "url": string;
    "watchers_count": number;
    "allow_auto_merge": boolean | null;
    "allow_forking": boolean | null;
    "allow_merge_commit": boolean | null;
    "allow_rebase_merge": boolean | null;
    "allow_squash_merge": boolean | null;
    "anonymous_access_enabled": boolean | null;
    "archive_url": string | null;
    "assignees_url": string | null;
    "auto_init": boolean | null;
    "blobs_url": string | null;
    "branches_url": string | null;
    "clone_url": string | null;
    "collaborators_url": string | null;
    "comments_url": string | null;
    "commits_url": string | null;
    "compare_url": string | null;
    "delete_branch_on_merge": boolean | null;
    "description": string | null;
    "forks_url": string | null;
    "git_commits_url": string | null;
    "git_refs_url": string | null;
    "git_tags_url": string | null;
    "git_url": string | null;
    "has_downloads": boolean | null;
    "has_issues": boolean | null;
    "has_projects": boolean | null;
    "has_wiki": boolean | null;
    "homepage": string | null;
    "is_template": boolean | null;
    "last_updated": Date | null;
    "master_branch": string | null;
    "merge_commit_message": string | null;
    "merge_commit_title": string | null;
    "merges_url": string | null;
    "milestones_url": string | null;
    "mirror_url": string | null;
    "network_count": number | null;
    "private": boolean | null;
    "pulls_url": string | null;
    "releases_url": string | null;
    "squash_merge_commit_message": string | null;
    "squash_merge_commit_title": string | null;
    "stargazers_url": string | null;
    "statuses_url": string | null;
    "subscribers_count": number | null;
    "subscribers_url": string | null;
    "subscription_url": string | null;
    "svn_url": string | null;
    "tags_url": string | null;
    "team_id": number | null;
    "teams_url": string | null;
    "temp_clone_token": string | null;
    "trees_url": string | null;
    "visibility": ("public" | "private") | null;
    "topics": Array<string>;
  };
} | null;

export function insertOrUpdatePackageJson(client: Executor, args: InsertOrUpdatePackageJsonArgs): Promise<InsertOrUpdatePackageJsonReturns> {
  return client.querySingle(`\
with 
  NewPackageJson := (
    insert PackageJson {
      name := <str>$name,
      package_version := <str>$package_version,
      repository := (
        select Repository
        filter .name = <str>$repository
        limit 1
      )
    }
    unless conflict on .repository 
    else (
      update PackageJson
      filter .repository.name = <str>$repository
      set {
        name := <str>$name,
        package_version := <str>$package_version,
        repository := (
          select Repository
          filter .name = <str>$repository
          limit 1
        ),
      }
    )
  ),

  InsertProdDependencies := (
    for dependency in array_unpack(<array<tuple<name: str, dependency_version: str>>>$dependencies)
    union (
      insert ProdDependency {
        name := <str>dependency.name,
        dependency_version := <str>dependency.dependency_version,
        package_json := NewPackageJson,
        repository := NewPackageJson.repository,
      }
      unless conflict on (.dependency_type, .name, .repository)
      else (
        update ProdDependency
        filter .name = <str>dependency.name
          and .repository = NewPackageJson.repository
        set {
          dependency_version := <str>dependency.dependency_version,
        }
      )
    )
  ),

  InsertDevDependencies := (
    for dev_dependency in array_unpack(<array<tuple<name: str, dependency_version: str>>>$dev_dependencies)
    union (
      insert DevDependency {
        name := <str>dev_dependency.name,
        dependency_version := <str>dev_dependency.dependency_version,
        package_json := NewPackageJson,
        repository := NewPackageJson.repository,
      }
      unless conflict on (.dependency_type, .name, .repository)
      else (
        update DevDependency
        filter .name = <str>dev_dependency.name
          and .repository = NewPackageJson.repository
        set {
          dependency_version := <str>dev_dependency.dependency_version,
        }
      )
    )
  )

select NewPackageJson { ** };`, args);

}


export type GetFilePathArgs = {
  readonly "repository_id"?: number | null;
};

export type GetFilePathReturns = {
  "file_name": string;
  "file_type": ("PNG" | "JPG" | "JPEG" | "GIF" | "SVG" | "PSD" | "JSON" | "MD" | "TXT" | "LOG" | "ZIP" | "GEL" | "TOML" | "YML" | "YAML" | "JSONC" | "WOFF2" | "CSS" | "TS" | "TSX" | "JS" | "EDGEQL" | "XML" | "PDF" | "CSV" | "SQL" | "HTML");
  "id": string;
  "path": string;
  "last_updated": Date | null;
  "repository": {
    "archived": boolean;
    "contents_url": string;
    "contributors_url": string;
    "created_at": string;
    "default_branch": string;
    "deployments_url": string;
    "disabled": boolean;
    "downloads_url": string;
    "events_url": string;
    "fork": boolean;
    "forks": number;
    "forks_count": number;
    "full_name": string;
    "has_discussions": boolean;
    "has_pages": boolean;
    "hooks_url": string;
    "html_url": string;
    "id": string;
    "issue_comment_url": string;
    "issue_events_url": string;
    "issues_url": string;
    "keys_url": string;
    "labels_url": string;
    "language": string;
    "languages_url": string;
    "name": string;
    "node_id": string;
    "notifications_url": string;
    "open_issues": number;
    "open_issues_count": number;
    "pushed_at": string;
    "repository_id": number;
    "size": number;
    "ssh_url": string;
    "stargazers_count": number;
    "updated_at": string;
    "url": string;
    "watchers_count": number;
    "allow_auto_merge": boolean | null;
    "allow_forking": boolean | null;
    "allow_merge_commit": boolean | null;
    "allow_rebase_merge": boolean | null;
    "allow_squash_merge": boolean | null;
    "anonymous_access_enabled": boolean | null;
    "archive_url": string | null;
    "assignees_url": string | null;
    "auto_init": boolean | null;
    "blobs_url": string | null;
    "branches_url": string | null;
    "clone_url": string | null;
    "collaborators_url": string | null;
    "comments_url": string | null;
    "commits_url": string | null;
    "compare_url": string | null;
    "delete_branch_on_merge": boolean | null;
    "description": string | null;
    "forks_url": string | null;
    "git_commits_url": string | null;
    "git_refs_url": string | null;
    "git_tags_url": string | null;
    "git_url": string | null;
    "has_downloads": boolean | null;
    "has_issues": boolean | null;
    "has_projects": boolean | null;
    "has_wiki": boolean | null;
    "homepage": string | null;
    "is_template": boolean | null;
    "last_updated": Date | null;
    "master_branch": string | null;
    "merge_commit_message": string | null;
    "merge_commit_title": string | null;
    "merges_url": string | null;
    "milestones_url": string | null;
    "mirror_url": string | null;
    "network_count": number | null;
    "private": boolean | null;
    "pulls_url": string | null;
    "releases_url": string | null;
    "squash_merge_commit_message": string | null;
    "squash_merge_commit_title": string | null;
    "stargazers_url": string | null;
    "statuses_url": string | null;
    "subscribers_count": number | null;
    "subscribers_url": string | null;
    "subscription_url": string | null;
    "svn_url": string | null;
    "tags_url": string | null;
    "team_id": number | null;
    "teams_url": string | null;
    "temp_clone_token": string | null;
    "trees_url": string | null;
    "visibility": ("public" | "private") | null;
    "topics": Array<string>;
  };
} | null;

export function getFilePath(client: Executor, args: GetFilePathArgs): Promise<GetFilePathReturns> {
  return client.querySingle(`\
# get FilePath by repoID
select assert_single(
  FilePath { ** }
  filter assert_exists(Repository.repository_id) ?= <optional int64>$repository_id
  and FilePath.file_type = FileType.JSON
) limit 1;`, args);

}


export type GetUserArgs = {
  readonly "login"?: string | null;
  readonly "user_id"?: number | null;
};

export type GetUserReturns = Array<{
  "avatar_url": string;
  "email": string;
  "id": string;
  "login": string;
  "name": string;
  "role_type": string;
  "site_admin": boolean;
  "user_id": number;
  "events_url": string | null;
  "followers_url": string | null;
  "following_url": string | null;
  "gists_url": string | null;
  "gravatar_id": string | null;
  "html_url": string | null;
  "last_updated": Date | null;
  "node_id": string | null;
  "organizations_url": string | null;
  "received_events_url": string | null;
  "repos_url": string | null;
  "starred_at": string | null;
  "starred_url": string | null;
  "subscriptions_url": string | null;
  "url": string | null;
  "user_view_type": string | null;
}>;

export function getUser(client: Executor, args: GetUserArgs): Promise<GetUserReturns> {
  return client.query(`\
select User { **
} filter assert_exists(User.user_id) ?= <optional int64>$user_id;

select User { **
} filter assert_exists(User.login) ?= <optional str>$login;

# This is all one query, but it's split up for readability. All filters are optional. 
# If no filters are provided, all Users will be returned.`, args);

}



export type GetAllPackageJsonsReturns = Array<{
  "id": string;
  "name": string;
  "package_version": string;
  "last_updated": Date | null;
  "dependencies": Array<{
    "dependency_version": string;
    "id": string;
    "name": string;
    "dependency_type": ("Dev" | "Prod") | null;
    "last_updated": Date | null;
  }>;
  "dev_dependencies": Array<{
    "dependency_version": string;
    "id": string;
    "name": string;
    "dependency_type": ("Dev" | "Prod") | null;
    "last_updated": Date | null;
  }>;
  "repository": {
    "archived": boolean;
    "contents_url": string;
    "contributors_url": string;
    "created_at": string;
    "default_branch": string;
    "deployments_url": string;
    "disabled": boolean;
    "downloads_url": string;
    "events_url": string;
    "fork": boolean;
    "forks": number;
    "forks_count": number;
    "full_name": string;
    "has_discussions": boolean;
    "has_pages": boolean;
    "hooks_url": string;
    "html_url": string;
    "id": string;
    "issue_comment_url": string;
    "issue_events_url": string;
    "issues_url": string;
    "keys_url": string;
    "labels_url": string;
    "language": string;
    "languages_url": string;
    "name": string;
    "node_id": string;
    "notifications_url": string;
    "open_issues": number;
    "open_issues_count": number;
    "pushed_at": string;
    "repository_id": number;
    "size": number;
    "ssh_url": string;
    "stargazers_count": number;
    "updated_at": string;
    "url": string;
    "watchers_count": number;
    "allow_auto_merge": boolean | null;
    "allow_forking": boolean | null;
    "allow_merge_commit": boolean | null;
    "allow_rebase_merge": boolean | null;
    "allow_squash_merge": boolean | null;
    "anonymous_access_enabled": boolean | null;
    "archive_url": string | null;
    "assignees_url": string | null;
    "auto_init": boolean | null;
    "blobs_url": string | null;
    "branches_url": string | null;
    "clone_url": string | null;
    "collaborators_url": string | null;
    "comments_url": string | null;
    "commits_url": string | null;
    "compare_url": string | null;
    "delete_branch_on_merge": boolean | null;
    "description": string | null;
    "forks_url": string | null;
    "git_commits_url": string | null;
    "git_refs_url": string | null;
    "git_tags_url": string | null;
    "git_url": string | null;
    "has_downloads": boolean | null;
    "has_issues": boolean | null;
    "has_projects": boolean | null;
    "has_wiki": boolean | null;
    "homepage": string | null;
    "is_template": boolean | null;
    "last_updated": Date | null;
    "master_branch": string | null;
    "merge_commit_message": string | null;
    "merge_commit_title": string | null;
    "merges_url": string | null;
    "milestones_url": string | null;
    "mirror_url": string | null;
    "network_count": number | null;
    "private": boolean | null;
    "pulls_url": string | null;
    "releases_url": string | null;
    "squash_merge_commit_message": string | null;
    "squash_merge_commit_title": string | null;
    "stargazers_url": string | null;
    "statuses_url": string | null;
    "subscribers_count": number | null;
    "subscribers_url": string | null;
    "subscription_url": string | null;
    "svn_url": string | null;
    "tags_url": string | null;
    "team_id": number | null;
    "teams_url": string | null;
    "temp_clone_token": string | null;
    "trees_url": string | null;
    "visibility": ("public" | "private") | null;
    "topics": Array<string>;
  };
}>;

export function getAllPackageJsons(client: Executor): Promise<GetAllPackageJsonsReturns> {
  return client.query(`\
# return all packageJsons
select PackageJson { ** };`);

}



export type GetTemplateRepositoriesReturns = Array<{
  "archived": boolean;
  "contents_url": string;
  "contributors_url": string;
  "created_at": string;
  "default_branch": string;
  "deployments_url": string;
  "disabled": boolean;
  "downloads_url": string;
  "events_url": string;
  "fork": boolean;
  "forks": number;
  "forks_count": number;
  "full_name": string;
  "has_discussions": boolean;
  "has_pages": boolean;
  "hooks_url": string;
  "html_url": string;
  "id": string;
  "issue_comment_url": string;
  "issue_events_url": string;
  "issues_url": string;
  "keys_url": string;
  "labels_url": string;
  "language": string;
  "languages_url": string;
  "name": string;
  "node_id": string;
  "notifications_url": string;
  "open_issues": number;
  "open_issues_count": number;
  "pushed_at": string;
  "repository_id": number;
  "size": number;
  "ssh_url": string;
  "stargazers_count": number;
  "updated_at": string;
  "url": string;
  "watchers_count": number;
  "allow_auto_merge": boolean | null;
  "allow_forking": boolean | null;
  "allow_merge_commit": boolean | null;
  "allow_rebase_merge": boolean | null;
  "allow_squash_merge": boolean | null;
  "anonymous_access_enabled": boolean | null;
  "archive_url": string | null;
  "assignees_url": string | null;
  "auto_init": boolean | null;
  "blobs_url": string | null;
  "branches_url": string | null;
  "clone_url": string | null;
  "collaborators_url": string | null;
  "comments_url": string | null;
  "commits_url": string | null;
  "compare_url": string | null;
  "delete_branch_on_merge": boolean | null;
  "description": string | null;
  "forks_url": string | null;
  "git_commits_url": string | null;
  "git_refs_url": string | null;
  "git_tags_url": string | null;
  "git_url": string | null;
  "has_downloads": boolean | null;
  "has_issues": boolean | null;
  "has_projects": boolean | null;
  "has_wiki": boolean | null;
  "homepage": string | null;
  "is_template": boolean | null;
  "last_updated": Date | null;
  "master_branch": string | null;
  "merge_commit_message": string | null;
  "merge_commit_title": string | null;
  "merges_url": string | null;
  "milestones_url": string | null;
  "mirror_url": string | null;
  "network_count": number | null;
  "private": boolean | null;
  "pulls_url": string | null;
  "releases_url": string | null;
  "squash_merge_commit_message": string | null;
  "squash_merge_commit_title": string | null;
  "stargazers_url": string | null;
  "statuses_url": string | null;
  "subscribers_count": number | null;
  "subscribers_url": string | null;
  "subscription_url": string | null;
  "svn_url": string | null;
  "tags_url": string | null;
  "team_id": number | null;
  "teams_url": string | null;
  "temp_clone_token": string | null;
  "trees_url": string | null;
  "visibility": ("public" | "private") | null;
  "all_dependencies": Array<{
    "dependency_version": string;
    "id": string;
    "name": string;
    "dependency_type": ("Dev" | "Prod") | null;
    "last_updated": Date | null;
  }>;
  "all_file_paths": Array<{
    "file_name": string;
    "file_type": ("PNG" | "JPG" | "JPEG" | "GIF" | "SVG" | "PSD" | "JSON" | "MD" | "TXT" | "LOG" | "ZIP" | "GEL" | "TOML" | "YML" | "YAML" | "JSONC" | "WOFF2" | "CSS" | "TS" | "TSX" | "JS" | "EDGEQL" | "XML" | "PDF" | "CSV" | "SQL" | "HTML");
    "id": string;
    "path": string;
    "last_updated": Date | null;
  }>;
  "package_json": Array<{
    "id": string;
    "name": string;
    "package_version": string;
    "last_updated": Date | null;
  }>;
  "topics": Array<string>;
  "owner": {
    "avatar_url": string;
    "email": string;
    "id": string;
    "login": string;
    "name": string;
    "role_type": string;
    "site_admin": boolean;
    "user_id": number;
    "events_url": string | null;
    "followers_url": string | null;
    "following_url": string | null;
    "gists_url": string | null;
    "gravatar_id": string | null;
    "html_url": string | null;
    "last_updated": Date | null;
    "node_id": string | null;
    "organizations_url": string | null;
    "received_events_url": string | null;
    "repos_url": string | null;
    "starred_at": string | null;
    "starred_url": string | null;
    "subscriptions_url": string | null;
    "url": string | null;
    "user_view_type": string | null;
  };
  "code_of_conduct": {
    "id": string;
    "key": string | null;
    "last_updated": Date | null;
    "name": string | null;
    "node_id": string | null;
    "spdx_id": string | null;
    "url": string | null;
  } | null;
  "license": {
    "id": string;
    "key": string;
    "name": string;
    "node_id": string;
    "html_url": string | null;
    "last_updated": Date | null;
    "spdx_id": string | null;
    "url": string | null;
  } | null;
  "organization": {
    "avatar_url": string;
    "events_url": string;
    "followers_url": string;
    "following_url": string;
    "gists_url": string;
    "gravatar_id": string;
    "html_url": string;
    "id": string;
    "login": string;
    "node_id": string;
    "organizations_url": string;
    "received_events_url": string;
    "repos_url": string;
    "role_type": string;
    "site_admin": boolean;
    "starred_url": string;
    "subscriptions_url": string;
    "url": string;
    "email": string | null;
    "last_updated": Date | null;
    "name": string | null;
    "organization_id": number | null;
    "starred_at": string | null;
    "user_view_type": string | null;
  } | null;
  "security_and_analysis": {
    "id": string;
    "advanced_security_status": string | null;
    "code_security_status": string | null;
    "dependabot_security_updates_status": string | null;
    "last_updated": Date | null;
    "secret_scanning_ai_detection_status": string | null;
    "secret_scanning_non_provider_patterns_status": string | null;
    "secret_scanning_push_protection_status": string | null;
    "secret_scanning_status": string | null;
  } | null;
  "template_repository": {
    "archived": boolean;
    "contents_url": string;
    "contributors_url": string;
    "created_at": string;
    "default_branch": string;
    "deployments_url": string;
    "disabled": boolean;
    "downloads_url": string;
    "events_url": string;
    "fork": boolean;
    "forks": number;
    "forks_count": number;
    "full_name": string;
    "has_discussions": boolean;
    "has_pages": boolean;
    "hooks_url": string;
    "html_url": string;
    "id": string;
    "issue_comment_url": string;
    "issue_events_url": string;
    "issues_url": string;
    "keys_url": string;
    "labels_url": string;
    "language": string;
    "languages_url": string;
    "name": string;
    "node_id": string;
    "notifications_url": string;
    "open_issues": number;
    "open_issues_count": number;
    "pushed_at": string;
    "repository_id": number;
    "size": number;
    "ssh_url": string;
    "stargazers_count": number;
    "updated_at": string;
    "url": string;
    "watchers_count": number;
    "allow_auto_merge": boolean | null;
    "allow_forking": boolean | null;
    "allow_merge_commit": boolean | null;
    "allow_rebase_merge": boolean | null;
    "allow_squash_merge": boolean | null;
    "anonymous_access_enabled": boolean | null;
    "archive_url": string | null;
    "assignees_url": string | null;
    "auto_init": boolean | null;
    "blobs_url": string | null;
    "branches_url": string | null;
    "clone_url": string | null;
    "collaborators_url": string | null;
    "comments_url": string | null;
    "commits_url": string | null;
    "compare_url": string | null;
    "delete_branch_on_merge": boolean | null;
    "description": string | null;
    "forks_url": string | null;
    "git_commits_url": string | null;
    "git_refs_url": string | null;
    "git_tags_url": string | null;
    "git_url": string | null;
    "has_downloads": boolean | null;
    "has_issues": boolean | null;
    "has_projects": boolean | null;
    "has_wiki": boolean | null;
    "homepage": string | null;
    "is_template": boolean | null;
    "last_updated": Date | null;
    "master_branch": string | null;
    "merge_commit_message": string | null;
    "merge_commit_title": string | null;
    "merges_url": string | null;
    "milestones_url": string | null;
    "mirror_url": string | null;
    "network_count": number | null;
    "private": boolean | null;
    "pulls_url": string | null;
    "releases_url": string | null;
    "squash_merge_commit_message": string | null;
    "squash_merge_commit_title": string | null;
    "stargazers_url": string | null;
    "statuses_url": string | null;
    "subscribers_count": number | null;
    "subscribers_url": string | null;
    "subscription_url": string | null;
    "svn_url": string | null;
    "tags_url": string | null;
    "team_id": number | null;
    "teams_url": string | null;
    "temp_clone_token": string | null;
    "trees_url": string | null;
    "visibility": ("public" | "private") | null;
    "topics": Array<string>;
  } | null;
  "user": {
    "avatar_url": string;
    "email": string;
    "id": string;
    "login": string;
    "name": string;
    "role_type": string;
    "site_admin": boolean;
    "user_id": number;
    "events_url": string | null;
    "followers_url": string | null;
    "following_url": string | null;
    "gists_url": string | null;
    "gravatar_id": string | null;
    "html_url": string | null;
    "last_updated": Date | null;
    "node_id": string | null;
    "organizations_url": string | null;
    "received_events_url": string | null;
    "repos_url": string | null;
    "starred_at": string | null;
    "starred_url": string | null;
    "subscriptions_url": string | null;
    "url": string | null;
    "user_view_type": string | null;
  } | null;
}>;

export function getTemplateRepositories(client: Executor): Promise<GetTemplateRepositoriesReturns> {
  return client.query(`\
select Repository { **
} filter (  
 .is_template = true
);`);

}


export type InsertOrUpdateRepositoryArgs = {
  readonly "archived": boolean;
  readonly "contents_url": string;
  readonly "contributors_url": string;
  readonly "created_at": string;
  readonly "default_branch": string;
  readonly "deployments_url": string;
  readonly "description": string;
  readonly "disabled": boolean;
  readonly "downloads_url": string;
  readonly "events_url": string;
  readonly "fork": boolean;
  readonly "forks": number;
  readonly "forks_count": number;
  readonly "full_name": string;
  readonly "has_discussions": boolean;
  readonly "has_issues": boolean;
  readonly "has_pages": boolean;
  readonly "has_projects": boolean;
  readonly "has_wiki": boolean;
  readonly "homepage": string;
  readonly "hooks_url": string;
  readonly "html_url": string;
  readonly "issue_comment_url": string;
  readonly "issue_events_url": string;
  readonly "issues_url": string;
  readonly "keys_url": string;
  readonly "labels_url": string;
  readonly "language": string;
  readonly "languages_url": string;
  readonly "license_key": string;
  readonly "license_name": string;
  readonly "license_node_id": string;
  readonly "license_spdx_id": string;
  readonly "license_url": string;
  readonly "name": string;
  readonly "node_id": string;
  readonly "notifications_url": string;
  readonly "open_issues": number;
  readonly "open_issues_count": number;
  readonly "owner_avatar_url": string;
  readonly "owner_email": string;
  readonly "owner_login": string;
  readonly "owner_name": string;
  readonly "owner_role_type": string;
  readonly "owner_site_admin": boolean;
  readonly "owner_user_id": number;
  readonly "private": boolean;
  readonly "pushed_at": string;
  readonly "repository_id": number;
  readonly "size": number;
  readonly "ssh_url": string;
  readonly "stargazers_count": number;
  readonly "template_repository_id": number;
  readonly "updated_at": string;
  readonly "url": string;
  readonly "watchers_count": number;
  readonly "allow_auto_merge"?: boolean | null;
  readonly "allow_forking"?: boolean | null;
  readonly "allow_merge_commit"?: boolean | null;
  readonly "allow_rebase_merge"?: boolean | null;
  readonly "allow_squash_merge"?: boolean | null;
  readonly "archive_url"?: string | null;
  readonly "assignees_url"?: string | null;
  readonly "blobs_url"?: string | null;
  readonly "branches_url"?: string | null;
  readonly "clone_url"?: string | null;
  readonly "collaborators_url"?: string | null;
  readonly "comments_url"?: string | null;
  readonly "commits_url"?: string | null;
  readonly "compare_url"?: string | null;
  readonly "delete_branch_on_merge"?: boolean | null;
  readonly "forks_url"?: string | null;
  readonly "git_commits_url"?: string | null;
  readonly "git_refs_url"?: string | null;
  readonly "git_tags_url"?: string | null;
  readonly "git_url"?: string | null;
  readonly "has_downloads"?: boolean | null;
  readonly "is_template"?: boolean | null;
  readonly "license_html_url"?: string | null;
  readonly "master_branch"?: string | null;
  readonly "merges_url"?: string | null;
  readonly "milestones_url"?: string | null;
  readonly "mirror_url"?: string | null;
  readonly "owner_events_url"?: string | null;
  readonly "owner_followers_url"?: string | null;
  readonly "owner_following_url"?: string | null;
  readonly "owner_gists_url"?: string | null;
  readonly "owner_gravatar_id"?: string | null;
  readonly "owner_html_url"?: string | null;
  readonly "owner_node_id"?: string | null;
  readonly "owner_organizations_url"?: string | null;
  readonly "owner_received_events_url"?: string | null;
  readonly "owner_repos_url"?: string | null;
  readonly "owner_starred_at"?: string | null;
  readonly "owner_starred_url"?: string | null;
  readonly "owner_subscriptions_url"?: string | null;
  readonly "owner_url"?: string | null;
  readonly "owner_user_view_type"?: string | null;
  readonly "pulls_url"?: string | null;
  readonly "releases_url"?: string | null;
  readonly "stargazers_url"?: string | null;
  readonly "statuses_url"?: string | null;
  readonly "subscribers_url"?: string | null;
  readonly "subscription_url"?: string | null;
  readonly "svn_url"?: string | null;
  readonly "tags_url"?: string | null;
  readonly "teams_url"?: string | null;
  readonly "topics"?: string | null;
  readonly "trees_url"?: string | null;
  readonly "visibility"?: string | null;
};

export type InsertOrUpdateRepositoryReturns = {
  "archived": boolean;
  "contents_url": string;
  "contributors_url": string;
  "created_at": string;
  "default_branch": string;
  "deployments_url": string;
  "disabled": boolean;
  "downloads_url": string;
  "events_url": string;
  "fork": boolean;
  "forks": number;
  "forks_count": number;
  "full_name": string;
  "has_discussions": boolean;
  "has_pages": boolean;
  "hooks_url": string;
  "html_url": string;
  "id": string;
  "issue_comment_url": string;
  "issue_events_url": string;
  "issues_url": string;
  "keys_url": string;
  "labels_url": string;
  "language": string;
  "languages_url": string;
  "name": string;
  "node_id": string;
  "notifications_url": string;
  "open_issues": number;
  "open_issues_count": number;
  "pushed_at": string;
  "repository_id": number;
  "size": number;
  "ssh_url": string;
  "stargazers_count": number;
  "updated_at": string;
  "url": string;
  "watchers_count": number;
  "allow_auto_merge": boolean | null;
  "allow_forking": boolean | null;
  "allow_merge_commit": boolean | null;
  "allow_rebase_merge": boolean | null;
  "allow_squash_merge": boolean | null;
  "anonymous_access_enabled": boolean | null;
  "archive_url": string | null;
  "assignees_url": string | null;
  "auto_init": boolean | null;
  "blobs_url": string | null;
  "branches_url": string | null;
  "clone_url": string | null;
  "collaborators_url": string | null;
  "comments_url": string | null;
  "commits_url": string | null;
  "compare_url": string | null;
  "delete_branch_on_merge": boolean | null;
  "description": string | null;
  "forks_url": string | null;
  "git_commits_url": string | null;
  "git_refs_url": string | null;
  "git_tags_url": string | null;
  "git_url": string | null;
  "has_downloads": boolean | null;
  "has_issues": boolean | null;
  "has_projects": boolean | null;
  "has_wiki": boolean | null;
  "homepage": string | null;
  "is_template": boolean | null;
  "last_updated": Date | null;
  "master_branch": string | null;
  "merge_commit_message": string | null;
  "merge_commit_title": string | null;
  "merges_url": string | null;
  "milestones_url": string | null;
  "mirror_url": string | null;
  "network_count": number | null;
  "private": boolean | null;
  "pulls_url": string | null;
  "releases_url": string | null;
  "squash_merge_commit_message": string | null;
  "squash_merge_commit_title": string | null;
  "stargazers_url": string | null;
  "statuses_url": string | null;
  "subscribers_count": number | null;
  "subscribers_url": string | null;
  "subscription_url": string | null;
  "svn_url": string | null;
  "tags_url": string | null;
  "team_id": number | null;
  "teams_url": string | null;
  "temp_clone_token": string | null;
  "trees_url": string | null;
  "visibility": ("public" | "private") | null;
  "all_dependencies": Array<{
    "dependency_version": string;
    "id": string;
    "name": string;
    "dependency_type": ("Dev" | "Prod") | null;
    "last_updated": Date | null;
  }>;
  "all_file_paths": Array<{
    "file_name": string;
    "file_type": ("PNG" | "JPG" | "JPEG" | "GIF" | "SVG" | "PSD" | "JSON" | "MD" | "TXT" | "LOG" | "ZIP" | "GEL" | "TOML" | "YML" | "YAML" | "JSONC" | "WOFF2" | "CSS" | "TS" | "TSX" | "JS" | "EDGEQL" | "XML" | "PDF" | "CSV" | "SQL" | "HTML");
    "id": string;
    "path": string;
    "last_updated": Date | null;
  }>;
  "package_json": Array<{
    "id": string;
    "name": string;
    "package_version": string;
    "last_updated": Date | null;
  }>;
  "topics": Array<string>;
  "owner": {
    "avatar_url": string;
    "email": string;
    "id": string;
    "login": string;
    "name": string;
    "role_type": string;
    "site_admin": boolean;
    "user_id": number;
    "events_url": string | null;
    "followers_url": string | null;
    "following_url": string | null;
    "gists_url": string | null;
    "gravatar_id": string | null;
    "html_url": string | null;
    "last_updated": Date | null;
    "node_id": string | null;
    "organizations_url": string | null;
    "received_events_url": string | null;
    "repos_url": string | null;
    "starred_at": string | null;
    "starred_url": string | null;
    "subscriptions_url": string | null;
    "url": string | null;
    "user_view_type": string | null;
  };
  "code_of_conduct": {
    "id": string;
    "key": string | null;
    "last_updated": Date | null;
    "name": string | null;
    "node_id": string | null;
    "spdx_id": string | null;
    "url": string | null;
  } | null;
  "license": {
    "id": string;
    "key": string;
    "name": string;
    "node_id": string;
    "html_url": string | null;
    "last_updated": Date | null;
    "spdx_id": string | null;
    "url": string | null;
  } | null;
  "organization": {
    "avatar_url": string;
    "events_url": string;
    "followers_url": string;
    "following_url": string;
    "gists_url": string;
    "gravatar_id": string;
    "html_url": string;
    "id": string;
    "login": string;
    "node_id": string;
    "organizations_url": string;
    "received_events_url": string;
    "repos_url": string;
    "role_type": string;
    "site_admin": boolean;
    "starred_url": string;
    "subscriptions_url": string;
    "url": string;
    "email": string | null;
    "last_updated": Date | null;
    "name": string | null;
    "organization_id": number | null;
    "starred_at": string | null;
    "user_view_type": string | null;
  } | null;
  "security_and_analysis": {
    "id": string;
    "advanced_security_status": string | null;
    "code_security_status": string | null;
    "dependabot_security_updates_status": string | null;
    "last_updated": Date | null;
    "secret_scanning_ai_detection_status": string | null;
    "secret_scanning_non_provider_patterns_status": string | null;
    "secret_scanning_push_protection_status": string | null;
    "secret_scanning_status": string | null;
  } | null;
  "template_repository": {
    "archived": boolean;
    "contents_url": string;
    "contributors_url": string;
    "created_at": string;
    "default_branch": string;
    "deployments_url": string;
    "disabled": boolean;
    "downloads_url": string;
    "events_url": string;
    "fork": boolean;
    "forks": number;
    "forks_count": number;
    "full_name": string;
    "has_discussions": boolean;
    "has_pages": boolean;
    "hooks_url": string;
    "html_url": string;
    "id": string;
    "issue_comment_url": string;
    "issue_events_url": string;
    "issues_url": string;
    "keys_url": string;
    "labels_url": string;
    "language": string;
    "languages_url": string;
    "name": string;
    "node_id": string;
    "notifications_url": string;
    "open_issues": number;
    "open_issues_count": number;
    "pushed_at": string;
    "repository_id": number;
    "size": number;
    "ssh_url": string;
    "stargazers_count": number;
    "updated_at": string;
    "url": string;
    "watchers_count": number;
    "allow_auto_merge": boolean | null;
    "allow_forking": boolean | null;
    "allow_merge_commit": boolean | null;
    "allow_rebase_merge": boolean | null;
    "allow_squash_merge": boolean | null;
    "anonymous_access_enabled": boolean | null;
    "archive_url": string | null;
    "assignees_url": string | null;
    "auto_init": boolean | null;
    "blobs_url": string | null;
    "branches_url": string | null;
    "clone_url": string | null;
    "collaborators_url": string | null;
    "comments_url": string | null;
    "commits_url": string | null;
    "compare_url": string | null;
    "delete_branch_on_merge": boolean | null;
    "description": string | null;
    "forks_url": string | null;
    "git_commits_url": string | null;
    "git_refs_url": string | null;
    "git_tags_url": string | null;
    "git_url": string | null;
    "has_downloads": boolean | null;
    "has_issues": boolean | null;
    "has_projects": boolean | null;
    "has_wiki": boolean | null;
    "homepage": string | null;
    "is_template": boolean | null;
    "last_updated": Date | null;
    "master_branch": string | null;
    "merge_commit_message": string | null;
    "merge_commit_title": string | null;
    "merges_url": string | null;
    "milestones_url": string | null;
    "mirror_url": string | null;
    "network_count": number | null;
    "private": boolean | null;
    "pulls_url": string | null;
    "releases_url": string | null;
    "squash_merge_commit_message": string | null;
    "squash_merge_commit_title": string | null;
    "stargazers_url": string | null;
    "statuses_url": string | null;
    "subscribers_count": number | null;
    "subscribers_url": string | null;
    "subscription_url": string | null;
    "svn_url": string | null;
    "tags_url": string | null;
    "team_id": number | null;
    "teams_url": string | null;
    "temp_clone_token": string | null;
    "trees_url": string | null;
    "visibility": ("public" | "private") | null;
    "topics": Array<string>;
  } | null;
  "user": {
    "avatar_url": string;
    "email": string;
    "id": string;
    "login": string;
    "name": string;
    "role_type": string;
    "site_admin": boolean;
    "user_id": number;
    "events_url": string | null;
    "followers_url": string | null;
    "following_url": string | null;
    "gists_url": string | null;
    "gravatar_id": string | null;
    "html_url": string | null;
    "last_updated": Date | null;
    "node_id": string | null;
    "organizations_url": string | null;
    "received_events_url": string | null;
    "repos_url": string | null;
    "starred_at": string | null;
    "starred_url": string | null;
    "subscriptions_url": string | null;
    "url": string | null;
    "user_view_type": string | null;
  } | null;
} | null;

export function insertOrUpdateRepository(client: Executor, args: InsertOrUpdateRepositoryArgs): Promise<InsertOrUpdateRepositoryReturns> {
  return client.querySingle(`\
with NewRepository := (insert Repository {
     repository_id:= <int64>$repository_id,
     archived:= <bool>$archived,
     contents_url:= <str>$contents_url,
     contributors_url:= <str>$contributors_url,
     created_at:= <str>$created_at,
     default_branch:= <str>$default_branch,
     deployments_url:= <str>$deployments_url,
     description:= <str>$description,
     disabled:= <bool>$disabled,
     downloads_url:= <str>$downloads_url,
     events_url:= <str>$events_url,
     fork:= <bool>$fork,
     forks:= <int64>$forks,
     forks_count:= <int64>$forks_count,
     full_name:= <str>$full_name,
     has_discussions:= <bool>$has_discussions,
     has_issues:= <bool>$has_issues,
     has_pages:= <bool>$has_pages,
     has_projects:= <bool>$has_projects,
     has_wiki:= <bool>$has_wiki,
     homepage:= <str>$homepage,
     hooks_url:= <str>$hooks_url,
     html_url:= <str>$html_url,
     issue_comment_url:= <str>$issue_comment_url,
     issue_events_url:= <str>$issue_events_url,
     issues_url:= <str>$issues_url,
     keys_url:= <str>$keys_url,
     labels_url:= <str>$labels_url,
     language:= <str>$language,
     languages_url:= <str>$languages_url,
     name:= <str>$name,
     node_id:= <str>$node_id,
     notifications_url:= <str>$notifications_url,
     open_issues:= <int64>$open_issues,
     open_issues_count:= <int64>$open_issues_count,
     owner:= (
        select User 
        # this is what the constraint exclusive is on
        filter .user_id = <int64>$owner_user_id
        limit 1
     ) ?? (
        insert User {
            avatar_url := <str>$owner_avatar_url,
            name := <str>$owner_name,
            email := <str>$owner_email, 
            login := <str>$owner_login,
            user_id := <int64>$owner_user_id,
            role_type := <str>$owner_role_type,
            site_admin := <bool>$owner_site_admin,
            events_url := <optional str>$owner_events_url,
            followers_url := <optional str>$owner_followers_url,
            following_url := <optional str>$owner_following_url,
            gists_url := <optional str>$owner_gists_url,
            gravatar_id := <optional str>$owner_gravatar_id, 
            html_url := <optional str>$owner_html_url,
            node_id := <optional str>$owner_node_id,
            organizations_url := <optional str>$owner_organizations_url,
            received_events_url := <optional str>$owner_received_events_url,
            repos_url := <optional str>$owner_repos_url,
            starred_url := <optional str>$owner_starred_url,
            starred_at := <optional str>$owner_starred_at,
            subscriptions_url := <optional str>$owner_subscriptions_url,
            url := <optional str>$owner_url,
            user_view_type := <optional str>$owner_user_view_type,
        }
     ),
    private:= <bool>$private,
    pushed_at:= <str>$pushed_at,
    url:= <str>$url,
    ssh_url:= <str>$ssh_url,
    size:= <int64>$size,
    stargazers_count:= <int64>$stargazers_count,
    updated_at:= <str>$updated_at,
    watchers_count:= <int64>$watchers_count,
    license := (
        select License 
        # this is what the constraint exclusive is on
        filter .name = <str>$license_name
        limit 1
    ) ?? (
        insert License {
            key := <str>$license_key,
            name := <str>$license_name,
            url := <str>$license_url,
            spdx_id := <str>$license_spdx_id,
            node_id := <str>$license_node_id,
            html_url := <optional str>$license_html_url,

        }
    ),
    archive_url:= <optional str>$archive_url,
    assignees_url:= <optional str>$assignees_url,
    blobs_url:= <optional str>$blobs_url,
    branches_url:= <optional str>$branches_url,
    clone_url:= <optional str>$clone_url,
    collaborators_url:= <optional str>$collaborators_url,
    comments_url:= <optional str>$comments_url,
    commits_url:= <optional str>$commits_url,
    compare_url:= <optional str>$compare_url,
    merges_url:= <optional str>$merges_url,
    milestones_url:= <optional str>$milestones_url,
    mirror_url:= <optional str>$mirror_url,
    git_commits_url:= <optional str>$git_commits_url,
    git_refs_url:= <optional str>$git_refs_url,
    git_tags_url:= <optional str>$git_tags_url,
    git_url:= <optional str>$git_url,
    stargazers_url:= <optional str>$stargazers_url,
    statuses_url:= <optional str>$statuses_url,
    subscribers_url:= <optional str>$subscribers_url,
    subscription_url:= <optional str>$subscription_url,
    pulls_url:= <optional str>$pulls_url,
    releases_url:= <optional str>$releases_url,
    svn_url:= <optional str>$svn_url,
    tags_url:= <optional str>$tags_url,
    teams_url:= <optional str>$teams_url,
    trees_url:= <optional str>$trees_url,
    allow_auto_merge:= <optional bool>$allow_auto_merge,
    allow_forking:= <optional bool>$allow_forking,
    allow_merge_commit:= <optional bool>$allow_merge_commit,
    allow_rebase_merge:= <optional bool>$allow_rebase_merge,
    allow_squash_merge:= <optional bool>$allow_squash_merge,
    delete_branch_on_merge:= <optional bool>$delete_branch_on_merge,
    forks_url:= <optional str>$forks_url,
    has_downloads:= <optional bool>$has_downloads,
    is_template:= <optional bool>$is_template,
    master_branch:= <optional str>$master_branch,
    template_repository:= 
        assert_single(
            (select detached Repository 
            filter detached Repository.repository_id = <int64>$template_repository_id limit 1)
        ),
    multi topics:= <optional str>$topics,
    visibility:= <optional str>$visibility,
    }
  unless conflict on .repository_id
  else (
    update Repository 
    filter .repository_id = <int64>$repository_id
    set {
     repository_id:= <int64>$repository_id,
     archived:= <bool>$archived,
     contents_url:= <str>$contents_url,
     contributors_url:= <str>$contributors_url,
     created_at:= <str>$created_at,
     default_branch:= <str>$default_branch,
     deployments_url:= <str>$deployments_url,
     description:= <str>$description,
     disabled:= <bool>$disabled,
     downloads_url:= <str>$downloads_url,
     events_url:= <str>$events_url,
     fork:= <bool>$fork,
     forks:= <int64>$forks,
     forks_count:= <int64>$forks_count,
     full_name:= <str>$full_name,
     has_discussions:= <bool>$has_discussions,
     has_issues:= <bool>$has_issues,
     has_pages:= <bool>$has_pages,
     has_projects:= <bool>$has_projects,
     has_wiki:= <bool>$has_wiki,
     homepage:= <str>$homepage,
     hooks_url:= <str>$hooks_url,
     html_url:= <str>$html_url,
     issue_comment_url:= <str>$issue_comment_url,
     issue_events_url:= <str>$issue_events_url,
     issues_url:= <str>$issues_url,
     keys_url:= <str>$keys_url,
     labels_url:= <str>$labels_url,
     language:= <str>$language,
     languages_url:= <str>$languages_url,
     name:= <str>$name,
     node_id:= <str>$node_id,
     notifications_url:= <str>$notifications_url,
     open_issues:= <int64>$open_issues,
     open_issues_count:= <int64>$open_issues_count,
     owner:= (
        select User 
        # this is what the constraint exclusive is on
        filter .user_id = <int64>$owner_user_id
        limit 1
     ) ?? (
        insert User {
            avatar_url := <str>$owner_avatar_url,
            name := <str>$owner_name,
            email := <str>$owner_email, 
            login := <str>$owner_login,
            user_id := <int64>$owner_user_id,
            role_type := <str>$owner_role_type,
            site_admin := <bool>$owner_site_admin,
            events_url := <optional str>$owner_events_url,
            followers_url := <optional str>$owner_followers_url,
            following_url := <optional str>$owner_following_url,
            gists_url := <optional str>$owner_gists_url,
            gravatar_id := <optional str>$owner_gravatar_id, 
            html_url := <optional str>$owner_html_url,
            node_id := <optional str>$owner_node_id,
            organizations_url := <optional str>$owner_organizations_url,
            received_events_url := <optional str>$owner_received_events_url,
            repos_url := <optional str>$owner_repos_url,
            starred_url := <optional str>$owner_starred_url,
            starred_at := <optional str>$owner_starred_at,
            subscriptions_url := <optional str>$owner_subscriptions_url,
            url := <optional str>$owner_url,
            user_view_type := <optional str>$owner_user_view_type,
        }
     ),
    private:= <bool>$private,
    pushed_at:= <str>$pushed_at,
    url:= <str>$url,
    ssh_url:= <str>$ssh_url,
    size:= <int64>$size,
    stargazers_count:= <int64>$stargazers_count,
    updated_at:= <str>$updated_at,
    watchers_count:= <int64>$watchers_count,
    license := (
        select License 
        # this is what the constraint exclusive is on
        filter .name = <str>$license_name
        limit 1
    ) ?? (
        insert License {
            key := <str>$license_key,
            name := <str>$license_name,
            url := <str>$license_url,
            spdx_id := <str>$license_spdx_id,
            node_id := <str>$license_node_id,
            html_url := <optional str>$license_html_url,

        }
    ),
    archive_url:= <optional str>$archive_url,
    assignees_url:= <optional str>$assignees_url,
    blobs_url:= <optional str>$blobs_url,
    branches_url:= <optional str>$branches_url,
    clone_url:= <optional str>$clone_url,
    collaborators_url:= <optional str>$collaborators_url,
    comments_url:= <optional str>$comments_url,
    commits_url:= <optional str>$commits_url,
    compare_url:= <optional str>$compare_url,
    merges_url:= <optional str>$merges_url,
    milestones_url:= <optional str>$milestones_url,
    mirror_url:= <optional str>$mirror_url,
    git_commits_url:= <optional str>$git_commits_url,
    git_refs_url:= <optional str>$git_refs_url,
    git_tags_url:= <optional str>$git_tags_url,
    git_url:= <optional str>$git_url,
    stargazers_url:= <optional str>$stargazers_url,
    statuses_url:= <optional str>$statuses_url,
    subscribers_url:= <optional str>$subscribers_url,
    subscription_url:= <optional str>$subscription_url,
    pulls_url:= <optional str>$pulls_url,
    releases_url:= <optional str>$releases_url,
    svn_url:= <optional str>$svn_url,
    tags_url:= <optional str>$tags_url,
    teams_url:= <optional str>$teams_url,
    trees_url:= <optional str>$trees_url,
    allow_auto_merge:= <optional bool>$allow_auto_merge,
    allow_forking:= <optional bool>$allow_forking,
    allow_merge_commit:= <optional bool>$allow_merge_commit,
    allow_rebase_merge:= <optional bool>$allow_rebase_merge,
    allow_squash_merge:= <optional bool>$allow_squash_merge,
    delete_branch_on_merge:= <optional bool>$delete_branch_on_merge,
    forks_url:= <optional str>$forks_url,
    has_downloads:= <optional bool>$has_downloads,
    is_template:= <optional bool>$is_template,
    master_branch:= <optional str>$master_branch,
    template_repository:= 
        assert_single(
            (select detached Repository 
            filter detached Repository.repository_id = <int64>$template_repository_id limit 1)
        ),
    multi topics:= <optional str>$topics,
    visibility:= <optional str>$visibility,
    }
  )
)
select NewRepository {**};`, args);

}


export type GetDependenciesForRepoArgs = {
  readonly "repository_id": number;
};

export type GetDependenciesForRepoReturns = Array<{
  "dependency_version": string;
  "id": string;
  "name": string;
  "dependency_type": ("Dev" | "Prod") | null;
  "last_updated": Date | null;
  "package_json": {
    "id": string;
    "name": string;
    "package_version": string;
    "last_updated": Date | null;
  };
  "repository": {
    "archived": boolean;
    "contents_url": string;
    "contributors_url": string;
    "created_at": string;
    "default_branch": string;
    "deployments_url": string;
    "disabled": boolean;
    "downloads_url": string;
    "events_url": string;
    "fork": boolean;
    "forks": number;
    "forks_count": number;
    "full_name": string;
    "has_discussions": boolean;
    "has_pages": boolean;
    "hooks_url": string;
    "html_url": string;
    "id": string;
    "issue_comment_url": string;
    "issue_events_url": string;
    "issues_url": string;
    "keys_url": string;
    "labels_url": string;
    "language": string;
    "languages_url": string;
    "name": string;
    "node_id": string;
    "notifications_url": string;
    "open_issues": number;
    "open_issues_count": number;
    "pushed_at": string;
    "repository_id": number;
    "size": number;
    "ssh_url": string;
    "stargazers_count": number;
    "updated_at": string;
    "url": string;
    "watchers_count": number;
    "allow_auto_merge": boolean | null;
    "allow_forking": boolean | null;
    "allow_merge_commit": boolean | null;
    "allow_rebase_merge": boolean | null;
    "allow_squash_merge": boolean | null;
    "anonymous_access_enabled": boolean | null;
    "archive_url": string | null;
    "assignees_url": string | null;
    "auto_init": boolean | null;
    "blobs_url": string | null;
    "branches_url": string | null;
    "clone_url": string | null;
    "collaborators_url": string | null;
    "comments_url": string | null;
    "commits_url": string | null;
    "compare_url": string | null;
    "delete_branch_on_merge": boolean | null;
    "description": string | null;
    "forks_url": string | null;
    "git_commits_url": string | null;
    "git_refs_url": string | null;
    "git_tags_url": string | null;
    "git_url": string | null;
    "has_downloads": boolean | null;
    "has_issues": boolean | null;
    "has_projects": boolean | null;
    "has_wiki": boolean | null;
    "homepage": string | null;
    "is_template": boolean | null;
    "last_updated": Date | null;
    "master_branch": string | null;
    "merge_commit_message": string | null;
    "merge_commit_title": string | null;
    "merges_url": string | null;
    "milestones_url": string | null;
    "mirror_url": string | null;
    "network_count": number | null;
    "private": boolean | null;
    "pulls_url": string | null;
    "releases_url": string | null;
    "squash_merge_commit_message": string | null;
    "squash_merge_commit_title": string | null;
    "stargazers_url": string | null;
    "statuses_url": string | null;
    "subscribers_count": number | null;
    "subscribers_url": string | null;
    "subscription_url": string | null;
    "svn_url": string | null;
    "tags_url": string | null;
    "team_id": number | null;
    "teams_url": string | null;
    "temp_clone_token": string | null;
    "trees_url": string | null;
    "visibility": ("public" | "private") | null;
    "topics": Array<string>;
  };
}>;

export function getDependenciesForRepo(client: Executor, args: GetDependenciesForRepoArgs): Promise<GetDependenciesForRepoReturns> {
  return client.query(`\
# Get all dependencies for a single repository by repository_id
select Dependency {
  **
} filter .repository.repository_id = <int64>$repository_id;`, args);

}


export type DeleteRepositoryArgs = {
  readonly "name": string;
  readonly "repository_id": number;
};

export type DeleteRepositoryReturns = Array<{
  "archived": boolean;
  "contents_url": string;
  "contributors_url": string;
  "created_at": string;
  "default_branch": string;
  "deployments_url": string;
  "disabled": boolean;
  "downloads_url": string;
  "events_url": string;
  "fork": boolean;
  "forks": number;
  "forks_count": number;
  "full_name": string;
  "has_discussions": boolean;
  "has_pages": boolean;
  "hooks_url": string;
  "html_url": string;
  "id": string;
  "issue_comment_url": string;
  "issue_events_url": string;
  "issues_url": string;
  "keys_url": string;
  "labels_url": string;
  "language": string;
  "languages_url": string;
  "name": string;
  "node_id": string;
  "notifications_url": string;
  "open_issues": number;
  "open_issues_count": number;
  "pushed_at": string;
  "repository_id": number;
  "size": number;
  "ssh_url": string;
  "stargazers_count": number;
  "updated_at": string;
  "url": string;
  "watchers_count": number;
  "allow_auto_merge": boolean | null;
  "allow_forking": boolean | null;
  "allow_merge_commit": boolean | null;
  "allow_rebase_merge": boolean | null;
  "allow_squash_merge": boolean | null;
  "anonymous_access_enabled": boolean | null;
  "archive_url": string | null;
  "assignees_url": string | null;
  "auto_init": boolean | null;
  "blobs_url": string | null;
  "branches_url": string | null;
  "clone_url": string | null;
  "collaborators_url": string | null;
  "comments_url": string | null;
  "commits_url": string | null;
  "compare_url": string | null;
  "delete_branch_on_merge": boolean | null;
  "description": string | null;
  "forks_url": string | null;
  "git_commits_url": string | null;
  "git_refs_url": string | null;
  "git_tags_url": string | null;
  "git_url": string | null;
  "has_downloads": boolean | null;
  "has_issues": boolean | null;
  "has_projects": boolean | null;
  "has_wiki": boolean | null;
  "homepage": string | null;
  "is_template": boolean | null;
  "last_updated": Date | null;
  "master_branch": string | null;
  "merge_commit_message": string | null;
  "merge_commit_title": string | null;
  "merges_url": string | null;
  "milestones_url": string | null;
  "mirror_url": string | null;
  "network_count": number | null;
  "private": boolean | null;
  "pulls_url": string | null;
  "releases_url": string | null;
  "squash_merge_commit_message": string | null;
  "squash_merge_commit_title": string | null;
  "stargazers_url": string | null;
  "statuses_url": string | null;
  "subscribers_count": number | null;
  "subscribers_url": string | null;
  "subscription_url": string | null;
  "svn_url": string | null;
  "tags_url": string | null;
  "team_id": number | null;
  "teams_url": string | null;
  "temp_clone_token": string | null;
  "trees_url": string | null;
  "visibility": ("public" | "private") | null;
  "all_dependencies": Array<{
    "dependency_version": string;
    "id": string;
    "name": string;
    "dependency_type": ("Dev" | "Prod") | null;
    "last_updated": Date | null;
  }>;
  "all_file_paths": Array<{
    "file_name": string;
    "file_type": ("PNG" | "JPG" | "JPEG" | "GIF" | "SVG" | "PSD" | "JSON" | "MD" | "TXT" | "LOG" | "ZIP" | "GEL" | "TOML" | "YML" | "YAML" | "JSONC" | "WOFF2" | "CSS" | "TS" | "TSX" | "JS" | "EDGEQL" | "XML" | "PDF" | "CSV" | "SQL" | "HTML");
    "id": string;
    "path": string;
    "last_updated": Date | null;
  }>;
  "package_json": Array<{
    "id": string;
    "name": string;
    "package_version": string;
    "last_updated": Date | null;
  }>;
  "topics": Array<string>;
  "owner": {
    "avatar_url": string;
    "email": string;
    "id": string;
    "login": string;
    "name": string;
    "role_type": string;
    "site_admin": boolean;
    "user_id": number;
    "events_url": string | null;
    "followers_url": string | null;
    "following_url": string | null;
    "gists_url": string | null;
    "gravatar_id": string | null;
    "html_url": string | null;
    "last_updated": Date | null;
    "node_id": string | null;
    "organizations_url": string | null;
    "received_events_url": string | null;
    "repos_url": string | null;
    "starred_at": string | null;
    "starred_url": string | null;
    "subscriptions_url": string | null;
    "url": string | null;
    "user_view_type": string | null;
  };
  "code_of_conduct": {
    "id": string;
    "key": string | null;
    "last_updated": Date | null;
    "name": string | null;
    "node_id": string | null;
    "spdx_id": string | null;
    "url": string | null;
  } | null;
  "license": {
    "id": string;
    "key": string;
    "name": string;
    "node_id": string;
    "html_url": string | null;
    "last_updated": Date | null;
    "spdx_id": string | null;
    "url": string | null;
  } | null;
  "organization": {
    "avatar_url": string;
    "events_url": string;
    "followers_url": string;
    "following_url": string;
    "gists_url": string;
    "gravatar_id": string;
    "html_url": string;
    "id": string;
    "login": string;
    "node_id": string;
    "organizations_url": string;
    "received_events_url": string;
    "repos_url": string;
    "role_type": string;
    "site_admin": boolean;
    "starred_url": string;
    "subscriptions_url": string;
    "url": string;
    "email": string | null;
    "last_updated": Date | null;
    "name": string | null;
    "organization_id": number | null;
    "starred_at": string | null;
    "user_view_type": string | null;
  } | null;
  "security_and_analysis": {
    "id": string;
    "advanced_security_status": string | null;
    "code_security_status": string | null;
    "dependabot_security_updates_status": string | null;
    "last_updated": Date | null;
    "secret_scanning_ai_detection_status": string | null;
    "secret_scanning_non_provider_patterns_status": string | null;
    "secret_scanning_push_protection_status": string | null;
    "secret_scanning_status": string | null;
  } | null;
  "template_repository": {
    "archived": boolean;
    "contents_url": string;
    "contributors_url": string;
    "created_at": string;
    "default_branch": string;
    "deployments_url": string;
    "disabled": boolean;
    "downloads_url": string;
    "events_url": string;
    "fork": boolean;
    "forks": number;
    "forks_count": number;
    "full_name": string;
    "has_discussions": boolean;
    "has_pages": boolean;
    "hooks_url": string;
    "html_url": string;
    "id": string;
    "issue_comment_url": string;
    "issue_events_url": string;
    "issues_url": string;
    "keys_url": string;
    "labels_url": string;
    "language": string;
    "languages_url": string;
    "name": string;
    "node_id": string;
    "notifications_url": string;
    "open_issues": number;
    "open_issues_count": number;
    "pushed_at": string;
    "repository_id": number;
    "size": number;
    "ssh_url": string;
    "stargazers_count": number;
    "updated_at": string;
    "url": string;
    "watchers_count": number;
    "allow_auto_merge": boolean | null;
    "allow_forking": boolean | null;
    "allow_merge_commit": boolean | null;
    "allow_rebase_merge": boolean | null;
    "allow_squash_merge": boolean | null;
    "anonymous_access_enabled": boolean | null;
    "archive_url": string | null;
    "assignees_url": string | null;
    "auto_init": boolean | null;
    "blobs_url": string | null;
    "branches_url": string | null;
    "clone_url": string | null;
    "collaborators_url": string | null;
    "comments_url": string | null;
    "commits_url": string | null;
    "compare_url": string | null;
    "delete_branch_on_merge": boolean | null;
    "description": string | null;
    "forks_url": string | null;
    "git_commits_url": string | null;
    "git_refs_url": string | null;
    "git_tags_url": string | null;
    "git_url": string | null;
    "has_downloads": boolean | null;
    "has_issues": boolean | null;
    "has_projects": boolean | null;
    "has_wiki": boolean | null;
    "homepage": string | null;
    "is_template": boolean | null;
    "last_updated": Date | null;
    "master_branch": string | null;
    "merge_commit_message": string | null;
    "merge_commit_title": string | null;
    "merges_url": string | null;
    "milestones_url": string | null;
    "mirror_url": string | null;
    "network_count": number | null;
    "private": boolean | null;
    "pulls_url": string | null;
    "releases_url": string | null;
    "squash_merge_commit_message": string | null;
    "squash_merge_commit_title": string | null;
    "stargazers_url": string | null;
    "statuses_url": string | null;
    "subscribers_count": number | null;
    "subscribers_url": string | null;
    "subscription_url": string | null;
    "svn_url": string | null;
    "tags_url": string | null;
    "team_id": number | null;
    "teams_url": string | null;
    "temp_clone_token": string | null;
    "trees_url": string | null;
    "visibility": ("public" | "private") | null;
    "topics": Array<string>;
  } | null;
  "user": {
    "avatar_url": string;
    "email": string;
    "id": string;
    "login": string;
    "name": string;
    "role_type": string;
    "site_admin": boolean;
    "user_id": number;
    "events_url": string | null;
    "followers_url": string | null;
    "following_url": string | null;
    "gists_url": string | null;
    "gravatar_id": string | null;
    "html_url": string | null;
    "last_updated": Date | null;
    "node_id": string | null;
    "organizations_url": string | null;
    "received_events_url": string | null;
    "repos_url": string | null;
    "starred_at": string | null;
    "starred_url": string | null;
    "subscriptions_url": string | null;
    "url": string | null;
    "user_view_type": string | null;
  } | null;
}>;

export function deleteRepository(client: Executor, args: DeleteRepositoryArgs): Promise<DeleteRepositoryReturns> {
  return client.query(`\
with DeletedRepository := (
    delete Repository 
    filter .repository_id = <int64>$repository_id or .name = <str>$name
)
select DeletedRepository {**};`, args);

}


export type GetRepositoryArgs = {
  readonly "name"?: string | null;
  readonly "repository_id"?: number | null;
};

export type GetRepositoryReturns = {
  "archived": boolean;
  "contents_url": string;
  "contributors_url": string;
  "created_at": string;
  "default_branch": string;
  "deployments_url": string;
  "disabled": boolean;
  "downloads_url": string;
  "events_url": string;
  "fork": boolean;
  "forks": number;
  "forks_count": number;
  "full_name": string;
  "has_discussions": boolean;
  "has_pages": boolean;
  "hooks_url": string;
  "html_url": string;
  "id": string;
  "issue_comment_url": string;
  "issue_events_url": string;
  "issues_url": string;
  "keys_url": string;
  "labels_url": string;
  "language": string;
  "languages_url": string;
  "name": string;
  "node_id": string;
  "notifications_url": string;
  "open_issues": number;
  "open_issues_count": number;
  "pushed_at": string;
  "repository_id": number;
  "size": number;
  "ssh_url": string;
  "stargazers_count": number;
  "updated_at": string;
  "url": string;
  "watchers_count": number;
  "allow_auto_merge": boolean | null;
  "allow_forking": boolean | null;
  "allow_merge_commit": boolean | null;
  "allow_rebase_merge": boolean | null;
  "allow_squash_merge": boolean | null;
  "anonymous_access_enabled": boolean | null;
  "archive_url": string | null;
  "assignees_url": string | null;
  "auto_init": boolean | null;
  "blobs_url": string | null;
  "branches_url": string | null;
  "clone_url": string | null;
  "collaborators_url": string | null;
  "comments_url": string | null;
  "commits_url": string | null;
  "compare_url": string | null;
  "delete_branch_on_merge": boolean | null;
  "description": string | null;
  "forks_url": string | null;
  "git_commits_url": string | null;
  "git_refs_url": string | null;
  "git_tags_url": string | null;
  "git_url": string | null;
  "has_downloads": boolean | null;
  "has_issues": boolean | null;
  "has_projects": boolean | null;
  "has_wiki": boolean | null;
  "homepage": string | null;
  "is_template": boolean | null;
  "last_updated": Date | null;
  "master_branch": string | null;
  "merge_commit_message": string | null;
  "merge_commit_title": string | null;
  "merges_url": string | null;
  "milestones_url": string | null;
  "mirror_url": string | null;
  "network_count": number | null;
  "private": boolean | null;
  "pulls_url": string | null;
  "releases_url": string | null;
  "squash_merge_commit_message": string | null;
  "squash_merge_commit_title": string | null;
  "stargazers_url": string | null;
  "statuses_url": string | null;
  "subscribers_count": number | null;
  "subscribers_url": string | null;
  "subscription_url": string | null;
  "svn_url": string | null;
  "tags_url": string | null;
  "team_id": number | null;
  "teams_url": string | null;
  "temp_clone_token": string | null;
  "trees_url": string | null;
  "visibility": ("public" | "private") | null;
  "all_dependencies": Array<{
    "dependency_version": string;
    "id": string;
    "name": string;
    "dependency_type": ("Dev" | "Prod") | null;
    "last_updated": Date | null;
  }>;
  "all_file_paths": Array<{
    "file_name": string;
    "file_type": ("PNG" | "JPG" | "JPEG" | "GIF" | "SVG" | "PSD" | "JSON" | "MD" | "TXT" | "LOG" | "ZIP" | "GEL" | "TOML" | "YML" | "YAML" | "JSONC" | "WOFF2" | "CSS" | "TS" | "TSX" | "JS" | "EDGEQL" | "XML" | "PDF" | "CSV" | "SQL" | "HTML");
    "id": string;
    "path": string;
    "last_updated": Date | null;
  }>;
  "package_json": Array<{
    "id": string;
    "name": string;
    "package_version": string;
    "last_updated": Date | null;
  }>;
  "topics": Array<string>;
  "owner": {
    "avatar_url": string;
    "email": string;
    "id": string;
    "login": string;
    "name": string;
    "role_type": string;
    "site_admin": boolean;
    "user_id": number;
    "events_url": string | null;
    "followers_url": string | null;
    "following_url": string | null;
    "gists_url": string | null;
    "gravatar_id": string | null;
    "html_url": string | null;
    "last_updated": Date | null;
    "node_id": string | null;
    "organizations_url": string | null;
    "received_events_url": string | null;
    "repos_url": string | null;
    "starred_at": string | null;
    "starred_url": string | null;
    "subscriptions_url": string | null;
    "url": string | null;
    "user_view_type": string | null;
  };
  "code_of_conduct": {
    "id": string;
    "key": string | null;
    "last_updated": Date | null;
    "name": string | null;
    "node_id": string | null;
    "spdx_id": string | null;
    "url": string | null;
  } | null;
  "license": {
    "id": string;
    "key": string;
    "name": string;
    "node_id": string;
    "html_url": string | null;
    "last_updated": Date | null;
    "spdx_id": string | null;
    "url": string | null;
  } | null;
  "organization": {
    "avatar_url": string;
    "events_url": string;
    "followers_url": string;
    "following_url": string;
    "gists_url": string;
    "gravatar_id": string;
    "html_url": string;
    "id": string;
    "login": string;
    "node_id": string;
    "organizations_url": string;
    "received_events_url": string;
    "repos_url": string;
    "role_type": string;
    "site_admin": boolean;
    "starred_url": string;
    "subscriptions_url": string;
    "url": string;
    "email": string | null;
    "last_updated": Date | null;
    "name": string | null;
    "organization_id": number | null;
    "starred_at": string | null;
    "user_view_type": string | null;
  } | null;
  "security_and_analysis": {
    "id": string;
    "advanced_security_status": string | null;
    "code_security_status": string | null;
    "dependabot_security_updates_status": string | null;
    "last_updated": Date | null;
    "secret_scanning_ai_detection_status": string | null;
    "secret_scanning_non_provider_patterns_status": string | null;
    "secret_scanning_push_protection_status": string | null;
    "secret_scanning_status": string | null;
  } | null;
  "template_repository": {
    "archived": boolean;
    "contents_url": string;
    "contributors_url": string;
    "created_at": string;
    "default_branch": string;
    "deployments_url": string;
    "disabled": boolean;
    "downloads_url": string;
    "events_url": string;
    "fork": boolean;
    "forks": number;
    "forks_count": number;
    "full_name": string;
    "has_discussions": boolean;
    "has_pages": boolean;
    "hooks_url": string;
    "html_url": string;
    "id": string;
    "issue_comment_url": string;
    "issue_events_url": string;
    "issues_url": string;
    "keys_url": string;
    "labels_url": string;
    "language": string;
    "languages_url": string;
    "name": string;
    "node_id": string;
    "notifications_url": string;
    "open_issues": number;
    "open_issues_count": number;
    "pushed_at": string;
    "repository_id": number;
    "size": number;
    "ssh_url": string;
    "stargazers_count": number;
    "updated_at": string;
    "url": string;
    "watchers_count": number;
    "allow_auto_merge": boolean | null;
    "allow_forking": boolean | null;
    "allow_merge_commit": boolean | null;
    "allow_rebase_merge": boolean | null;
    "allow_squash_merge": boolean | null;
    "anonymous_access_enabled": boolean | null;
    "archive_url": string | null;
    "assignees_url": string | null;
    "auto_init": boolean | null;
    "blobs_url": string | null;
    "branches_url": string | null;
    "clone_url": string | null;
    "collaborators_url": string | null;
    "comments_url": string | null;
    "commits_url": string | null;
    "compare_url": string | null;
    "delete_branch_on_merge": boolean | null;
    "description": string | null;
    "forks_url": string | null;
    "git_commits_url": string | null;
    "git_refs_url": string | null;
    "git_tags_url": string | null;
    "git_url": string | null;
    "has_downloads": boolean | null;
    "has_issues": boolean | null;
    "has_projects": boolean | null;
    "has_wiki": boolean | null;
    "homepage": string | null;
    "is_template": boolean | null;
    "last_updated": Date | null;
    "master_branch": string | null;
    "merge_commit_message": string | null;
    "merge_commit_title": string | null;
    "merges_url": string | null;
    "milestones_url": string | null;
    "mirror_url": string | null;
    "network_count": number | null;
    "private": boolean | null;
    "pulls_url": string | null;
    "releases_url": string | null;
    "squash_merge_commit_message": string | null;
    "squash_merge_commit_title": string | null;
    "stargazers_url": string | null;
    "statuses_url": string | null;
    "subscribers_count": number | null;
    "subscribers_url": string | null;
    "subscription_url": string | null;
    "svn_url": string | null;
    "tags_url": string | null;
    "team_id": number | null;
    "teams_url": string | null;
    "temp_clone_token": string | null;
    "trees_url": string | null;
    "visibility": ("public" | "private") | null;
    "topics": Array<string>;
  } | null;
  "user": {
    "avatar_url": string;
    "email": string;
    "id": string;
    "login": string;
    "name": string;
    "role_type": string;
    "site_admin": boolean;
    "user_id": number;
    "events_url": string | null;
    "followers_url": string | null;
    "following_url": string | null;
    "gists_url": string | null;
    "gravatar_id": string | null;
    "html_url": string | null;
    "last_updated": Date | null;
    "node_id": string | null;
    "organizations_url": string | null;
    "received_events_url": string | null;
    "repos_url": string | null;
    "starred_at": string | null;
    "starred_url": string | null;
    "subscriptions_url": string | null;
    "url": string | null;
    "user_view_type": string | null;
  } | null;
} | null;

export function getRepository(client: Executor, args: GetRepositoryArgs): Promise<GetRepositoryReturns> {
  return client.querySingle(`\
select Repository { **
} filter (
  assert_exists(Repository.repository_id) ?= <optional int64>$repository_id or
  assert_exists(Repository.full_name) ?= <optional str>$name or
  assert_exists(Repository.name) ?= <optional str>$name
) limit 1;`, args);

}
