on:
  workflow_dispatch:
    inputs:
      repo_name:
        description: "Name of the repository to update"
        required: true
        type: string
      pr_title:
        description: "Title for the pull request"
        required: true
        type: string
      pr_body:
        description: "Description for the pull request"
        required: true
        type: string
      owner:
        description: "GitHub organization or user name"
        required: true
        type: string
      gh_access_token:
        description: "GitHub API token for authentication"
        required: true
        type: string
      component_path:
        description: "Path where the component should be created"
        required: true
        type: string
      component_contents:
        description: "Contents of the component file"
        required: true
        type: string

jobs:
  update-package:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ inputs.gh_access_token }}
          repository: ${{ inputs.owner }}/${{ inputs.repo_name }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Create component file
        run: |
          mkdir -p ${{dirname inputs.component_path }}
          echo "${{ inputs.component_contents }}" > ${{ inputs.component_path }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ inputs.gh_access_token }}
          commit-message: "Copy component"
          title: "Copy component"
          body: "Copy component"
          branch: copy-component-${{ inputs.repo_name }}
          base: main
